import mongoose from 'mongoose'
const { Schema } = mongoose

const AbankSchema = new Schema({
  id: { type: Number }, // id int(11)
  code: { type: Number }, // CODE int(11)
  ccode: { type: Number }, // CCODE int(11)
  drCr: { type: String }, // DR_CR varchar(1)
  vno: { type: Number }, // VNO int(11)
  amount: { type: String }, // AMOUNT varchar(14)
  date: { type: String }, // DATE varchar(10)
  narr: { type: String }, // NARR varchar(40)
  cnarr: { type: String }, // CNARR varchar(40)
  cnarr1: { type: String }, // CNARR1 varchar(40)
  recno: { type: String }, // RECNO varchar(12)
  edate: { type: String }, // EDATE varchar(10)
  flint: { type: String }, // FLINT varchar(1)
  jcode: { type: Number }, // JCODE int(11)
  username: { type: String }, // USERNAME varchar(10)
  chNo: { type: String }, // CH_NO varchar(10)
  chDate: { type: String }, // CH_DATE varchar(10)
  cleardate: { type: String }, // CLEARDATE varchar(10)
  bankflg: { type: String }, // BANKFLG varchar(10)
  cstVat: { type: String }, // CST_VAT varchar(10)
  taxfrom: { type: String }, // TAXFROM varchar(10)
  taxto: { type: String }, // TAXTO varchar(10)
  taxtype: { type: String }, // TAXTYPE varchar(10)
  depositdat: { type: String }, // DEPOSITDAT varchar(10)
  challanno: { type: String }, // CHALLANNO varchar(10)
  bankcode: { type: String }, // BANKCODE varchar(10)
  bankname: { type: String }, // BANKNAME varchar(10)
  partycode: { type: String }, // PARTYCODE varchar(12)
  upstcode: { type: Number }, // UPSTCODE int(11)
  upstamt: { type: String }, // UPSTAMT varchar(7)
  upsttamt: { type: String }, // UPSTTAMT varchar(7)
  cesscode: { type: Number }, // CESSCODE int(11)
  cessamt: { type: String }, // CESSAMT varchar(7)
  cesstamt: { type: String }, // CESSTAMT varchar(7)
  schcode: { type: Number }, // SCHCODE int(11)
  schamt: { type: String }, // SCHAMT varchar(7)
  schtamt: { type: String }, // SCHTAMT varchar(7)
  bno: { type: String }, // BNO varchar(3)
}, { timestamps: false })

export default mongoose.model('Abank', AbankSchema, 'abank')
