import mongoose from 'mongoose'
const { Schema } = mongoose

const ApharmaSchema = new Schema({
  fl: { type: String }, // FL varchar(255)
  pcode: { type: String }, // PCODE varchar(255)
  name: { type: String }, // NAME varchar(255)
  head: { type: String }, // HEAD varchar(255)
  des: { type: String }, // DES varchar(255)
  des1: { type: String }, // DES1 varchar(255)
  cdes: { type: String }, // CDES varchar(255)
  bk: { type: String }, // BK varchar(255)
  limit1: { type: String }, // LIMIT1 varchar(255)
  limit2: { type: String }, // LIMIT2 varchar(255)
  condition1: { type: String }, // CONDITION1 varchar(255)
  condition: { type: String }, // CONDITION varchar(255)
  logic: { type: String }, // LOGIC varchar(255)
  phid: { type: String }, // PHID varchar(255)
  rid: { type: String }, // RID varchar(255)
  formu: { type: String }, // FORMU varchar(255)
  sprefNo: { type: String }, // SPREF_NO varchar(255)
  ver: { type: String }, // VER varchar(255)
  verDate: { type: String }, // VER_DATE varchar(255)
  stpNo: { type: String }, // STP_NO varchar(255)
  stsNo: { type: String }, // STS_NO varchar(255)
  stsNo1: { type: String }, // STS_NO1 varchar(255)
  stsNo2: { type: String }, // STS_NO2 varchar(255)
  grade: { type: String }, // GRADE varchar(255)
  units: { type: String }, // UNITS varchar(255)
  limits: { type: String }, // LIMITS varchar(255)
  method: { type: String }, // METHOD varchar(255)
  reportflag: { type: String }, // REPORTFLAG varchar(255)
  mainsub: { type: String }, // MAINSUB varchar(255)
  division: { type: String }, // DIVISION varchar(255)
  nablflag: { type: String }, // NABLFLAG varchar(255)
  limits1: { type: String }, // LIMITS1 varchar(255)
  stsNo3: { type: String }, // STS_NO3 varchar(255)
  stsNo4: { type: String }, // STS_NO4 varchar(255)
  stpNoa: { type: String }, // STP_NOA varchar(255)
  stpNob: { type: String }, // STP_NOB varchar(255)
  stsNo5: { type: String }, // STS_NO5 varchar(255)
  stsNo6: { type: String }, // STS_NO6 varchar(255)
  narr: { type: String }, // NARR varchar(255)
  narr1: { type: String }, // NARR1 varchar(255)
  excfl: { type: String }, // EXCFL varchar(255)
  pharmaflg: { type: String }, // PHARMAFLG varchar(255)
  refDoc: { type: String }, // REF_DOC varchar(255)
  instid: { type: String }, // INSTID varchar(255)
  clause: { type: String }, // CLAUSE varchar(255)
  head1: { type: String }, // HEAD1 varchar(255)
  stsNo7: { type: String }, // STS_NO7 varchar(255)
  psrno: { type: String }, // PSRNO varchar(255)
  cldata: { type: String }, // CLDATA varchar(255)
  part: { type: String }, // PART varchar(255)
}, { timestamps: false })

export default mongoose.model('Apharma', ApharmaSchema, 'apharma')
