import mongoose from 'mongoose'
const { Schema } = mongoose

const AsalehdSchema = new Schema({
  id: { type: Number }, // id int(11)
  fl: { type: String }, // FL varchar(10)
  typeField: { type: String }, // TYPE varchar(2)
  bno: { type: String }, // BNO varchar(15)
  bdate: { type: String }, // BDATE varchar(10)
  code: { type: String }, // CODE varchar(12)
  name: { type: String }, // NAME varchar(40)
  amount: { type: String }, // AMOUNT varchar(13)
  netamt: { type: String }, // NETAMT varchar(13)
  netamt1: { type: String }, // NETAMT1 varchar(8)
  narr: { type: String }, // NARR varchar(180)
  upstamt: { type: String }, // UPSTAMT varchar(9)
  upsttamt: { type: String }, // UPSTTAMT varchar(12)
  upstcode: { type: Number }, // UPSTCODE int(11)
  tdcode: { type: Number }, // TDCODE int(11)
  cesscode: { type: Number }, // CESSCODE int(11)
  cessamt: { type: String }, // CESSAMT varchar(8)
  cesstamt: { type: String }, // CESSTAMT varchar(10)
  schcode: { type: Number }, // SCHCODE int(11)
  schamt: { type: String }, // SCHAMT varchar(8)
  schtamt: { type: String }, // SCHTAMT varchar(9)
  recpayment: { type: String }, // RECPAYMENT varchar(7)
  paymentflg: { type: String }, // PAYMENTFLG varchar(1)
  recpamt: { type: String }, // RECPAMT varchar(13)
  rectdsamt: { type: String }, // RECTDSAMT varchar(12)
  recdisamt: { type: String }, // RECDISAMT varchar(10)
  tdamt: { type: String }, // TDAMT varchar(9)
  tdtamt: { type: String }, // TDTAMT varchar(13)
  station: { type: String }, // STATION varchar(25)
  stat: { type: String }, // STAT varchar(20)
  srNo: { type: Number }, // SR_NO int(11)
  rem: { type: String }, // REM varchar(10)
  username: { type: String }, // USERNAME varchar(6)
  fbdate: { type: String }, // FBDATE varchar(10)
  tbdate: { type: String }, // TBDATE varchar(10)
  slid: { type: String }, // SLID varchar(10)
  scode: { type: Number }, // SCODE int(11)
  amount1: { type: String }, // AMOUNT1 varchar(7)
  disamt: { type: String }, // DISAMT varchar(7)
  bcode: { type: String }, // BCODE varchar(7)
  refNo: { type: String }, // REF_NO varchar(10)
  saletype: { type: String }, // SALETYPE varchar(10)
  manualcode: { type: String }, // MANUALCODE varchar(10)
  gtype: { type: String }, // GTYPE varchar(10)
  gcode: { type: String }, // GCODE varchar(7)
  ptycode: { type: String }, // PTYCODE varchar(12)
  ptyname: { type: String }, // PTYNAME varchar(10)
  colcharge: { type: String }, // COLCHARGE varchar(7)
  foodexp: { type: String }, // FOODEXP varchar(7)
  travexp: { type: String }, // TRAVEXP varchar(7)
}, { timestamps: false })

export default mongoose.model('Asalehd', AsalehdSchema, 'asalehd')
