import mongoose from 'mongoose'
const { Schema } = mongoose

const AttendanceregisterSchema = new Schema({
  id: { type: Number }, // id int(11)
  enterby: { type: Number }, // enterby int(11)
  enterdatetime: { type: Date }, // enterdatetime datetime
  eid: { type: Number }, // eid int(11)
  month: { type: Number }, // month int(11)
  year: { type: Number }, // year int(11)
  f1Intme: { type: String }, // 1_intme varchar(20)
  f1Outtme: { type: String }, // 1_outtme varchar(20)
  f2Intme: { type: String }, // 2_intme varchar(20)
  f2Outtme: { type: String }, // 2_outtme varchar(20)
  f3Intme: { type: String }, // 3_intme varchar(20)
  f3Outtme: { type: String }, // 3_outtme varchar(20)
  f4Intme: { type: String }, // 4_intme varchar(20)
  f4Outtme: { type: String }, // 4_outtme varchar(20)
  f5Intme: { type: String }, // 5_intme varchar(20)
  f5Outtme: { type: String }, // 5_outtme varchar(20)
  f6Intme: { type: String }, // 6_intme varchar(20)
  f6Outtme: { type: String }, // 6_outtme varchar(20)
  f7Intme: { type: String }, // 7_intme varchar(20)
  f7Outtme: { type: String }, // 7_outtme varchar(20)
  f8Intme: { type: String }, // 8_intme varchar(20)
  f8Outtme: { type: String }, // 8_outtme varchar(20)
  f9Intme: { type: String }, // 9_intme varchar(20)
  f9Outtme: { type: String }, // 9_outtme varchar(20)
  f10Intme: { type: String }, // 10_intme varchar(20)
  f10Outtme: { type: String }, // 10_outtme varchar(20)
  f11Intme: { type: String }, // 11_intme varchar(20)
  f11Outtme: { type: String }, // 11_outtme varchar(20)
  f12Intme: { type: String }, // 12_intme varchar(20)
  f12Outtme: { type: String }, // 12_outtme varchar(20)
  f13Intme: { type: String }, // 13_intme varchar(20)
  f13Outtme: { type: String }, // 13_outtme varchar(20)
  f14Intme: { type: String }, // 14_intme varchar(20)
  f14Outtme: { type: String }, // 14_outtme varchar(20)
  f15Intme: { type: String }, // 15_intme varchar(20)
  f15Outtme: { type: String }, // 15_outtme varchar(20)
  f16Intme: { type: String }, // 16_intme varchar(20)
  f16Outtme: { type: String }, // 16_outtme varchar(20)
  f17Intme: { type: String }, // 17_intme varchar(20)
  f17Outtme: { type: String }, // 17_outtme varchar(20)
  f18Intme: { type: String }, // 18_intme varchar(20)
  f18Outtme: { type: String }, // 18_outtme varchar(20)
  f19Intme: { type: String }, // 19_intme varchar(20)
  f19Outtme: { type: String }, // 19_outtme varchar(20)
  f20Intme: { type: String }, // 20_intme varchar(20)
  f20Outtme: { type: String }, // 20_outtme varchar(20)
  f21Intme: { type: String }, // 21_intme varchar(20)
  f21Outtme: { type: String }, // 21_outtme varchar(20)
  f22Intme: { type: String }, // 22_intme varchar(20)
  f22Outtme: { type: String }, // 22_outtme varchar(20)
  f23Intme: { type: String }, // 23_intme varchar(20)
  f23Outtme: { type: String }, // 23_outtme varchar(20)
  f24Intme: { type: String }, // 24_intme varchar(20)
  f24Outtme: { type: String }, // 24_outtme varchar(20)
  f25Intme: { type: String }, // 25_intme varchar(20)
  f25Outtme: { type: String }, // 25_outtme varchar(20)
  f26Intme: { type: String }, // 26_intme varchar(20)
  f26Outtme: { type: String }, // 26_outtme varchar(20)
  f27Intme: { type: String }, // 27_intme varchar(20)
  f27Outtme: { type: String }, // 27_outtme varchar(20)
  f28Intme: { type: String }, // 28_intme varchar(20)
  f28Outtme: { type: String }, // 28_outtme varchar(20)
  f29Intme: { type: String }, // 29_intme varchar(20)
  f29Outtme: { type: String }, // 29_outtme varchar(20)
  f30Intme: { type: String }, // 30_intme varchar(20)
  f30Outtme: { type: String }, // 30_outtme varchar(20)
  f31Intme: { type: String }, // 31_intme varchar(20)
  f31Outtme: { type: String }, // 31_outtme varchar(20)
  totalhours: { type: Number }, // totalhours float
  presentdays: { type: Number }, // presentdays float
  absentdays: { type: Number }, // absentdays float
  leavedays: { type: Number }, // leavedays float
  holidays: { type: Number }, // holidays float
  totalcl: { type: Number }, // totalcl float
  totalpl: { type: Number }, // totalpl float
  totalel: { type: Number }, // totalel float
  totalul: { type: Number }, // totalul float
  totalsl: { type: Number }, // totalsl float
  totalhcl: { type: Number }, // totalhcl float
  totalhpl: { type: Number }, // totalhpl float
  totalhel: { type: Number }, // totalhel float
  totalhul: { type: Number }, // totalhul float
  totalhsl: { type: Number }, // totalhsl float
  latemark1: { type: Number }, // latemark1 int(11)
  dayworked: { type: Number }, // dayworked float
  sundays: { type: Number }, // sundays float
  totalhalfdays: { type: Number }, // totalhalfdays int(11)
  earlygoing2: { type: Number }, // earlygoing2 int(11)
  ph: { type: Number }, // ph int(11)
  pd: { type: Number }, // pd int(11)
  wo: { type: Number }, // wo int(11)
  pl: { type: Number }, // pl int(11)
  cl: { type: Number }, // cl int(11)
  sl: { type: Number }, // sl int(11)
  totaldays: { type: Number }, // totaldays int(11)
  monthdays: { type: Number }, // monthdays int(11)
  ab: { type: Number }, // ab int(11)
  wd: { type: Number }, // wd int(11)
  halfdays: { type: Number }, // halfdays decimal(15
  ontmedays: { type: Number }, // ontmedays float
  latemark2: { type: Number }, // latemark2 int(11)
  latemarkdays: { type: Number }, // latemarkdays float
  lcDays: { type: Number }, // lc_days int(11)
  lwhDays: { type: Number }, // lwh_days int(11)
  column90: { type: Number }, // Column 90 float
  earlygoingdays: { type: Number }, // earlygoingdays float
  otdays: { type: Number }, // otdays int(11)
  misspunchdays: { type: Number }, // misspunchdays float
  elopening: { type: Number }, // elopening float
  elearned: { type: Number }, // elearned float
  elused: { type: Number }, // elused float
  elclosing: { type: Number }, // elclosing float
  company: { type: Number }, // company int(11)
  branch: { type: Number }, // branch int(11)
  overtme: { type: Number }, // overtme int(11)
  workingWo: { type: Number }, // working_wo int(11)
}, { timestamps: false })

export default mongoose.model('Attendanceregister', AttendanceregisterSchema, 'attendanceregister')
