import mongoose from 'mongoose'
const { Schema } = mongoose

const BomSchema = new Schema({
  id: { type: Number }, // id int(11)
  bomName: { type: String }, // bom_name varchar(255)
  pid: { type: Number }, // pid int(11)
  project: { type: Number }, // project int(11)
  recipydate: { type: Date }, // recipydate date
  discount: { type: Number }, // discount float
  othercharges: { type: Number }, // othercharges float
  total: { type: Number }, // total float
  company: { type: Number }, // company int(11)
  branch: { type: Number }, // branch int(11)
  grosstotal: { type: Number }, // grosstotal float
  difference: { type: Number }, // difference float
  transportationcharges: { type: Number }, // transportationcharges float
  temprature: { type: String }, // temprature varchar(10)
  fuel: { type: String }, // fuel varchar(10)
  elecricity: { type: String }, // elecricity varchar(10)
  labour: { type: String }, // labour varchar(10)
  packagingcost: { type: String }, // packagingcost varchar(10)
  manufacturingtme: { type: String }, // manufacturingtme varchar(10)
  packagingtme: { type: String }, // packagingtme varchar(10)
  productlife: { type: String }, // productlife varchar(10)
  abnormalloss: { type: String }, // abnormalloss varchar(10)
  normalloss: { type: String }, // normalloss varchar(10)
  electricity: { type: String }, // electricity varchar(100)
  tempratureC: { type: Number }, // temprature_c float
  image1: { type: String }, // image1 varchar(255)
  method: { type: String }, // method varchar(255)
  wrightkachha: { type: Number }, // wrightkachha float
  wrightpakka: { type: Number }, // wrightpakka float
  productionRatePer: { type: Number }, // production_rate_per float
  purchaserate: { type: Number }, // purchaserate float
  coolingtme: { type: String }, // coolingtme varchar(25)
  actualtotal: { type: Number }, // actualtotal float
  tempratureinrs: { type: Number }, // tempratureinrs float
  tempratureinper: { type: Number }, // tempratureinper float
  fuelinrs: { type: Number }, // fuelinrs float
  fuelinper: { type: Number }, // fuelinper float
  electricityinrs: { type: Number }, // electricityinrs float
  electricityinper: { type: Number }, // electricityinper float
  labourinrs: { type: Number }, // labourinrs float
  labourinper: { type: Number }, // labourinper float
  packagingcostinrs: { type: Number }, // packagingcostinrs float
  packagingcostinper: { type: Number }, // packagingcostinper float
  otherchargesinrs: { type: Number }, // otherchargesinrs float
  otherchargesinper: { type: Number }, // otherchargesinper float
  normallossinrs: { type: Number }, // normallossinrs float
  normallossinper: { type: Number }, // normallossinper float
  abnormallossinrs: { type: Number }, // abnormallossinrs float
  abnormallossinper: { type: Number }, // abnormallossinper float
  transportationchargesinrs: { type: Number }, // transportationchargesinrs float
  transportationchargesinper: { type: Number }, // transportationchargesinper float
  total1: { type: Number }, // total1 float
  totalqty: { type: Number }, // totalqty float
  totalqty1: { type: Number }, // totalqty1 float
  machinerydepreciation: { type: Number }, // machinerydepreciation float
  machinerydepreciationper: { type: Number }, // machinerydepreciationper float
  deleteField: { type: Number }, // delete int(11)
  active: { type: Number }, // active int(11)
  datetime: { type: Date }, // datetime datetime
  unit: { type: Number }, // unit int(11)
  enterby: { type: Number }, // enterby int(11)
  enterdatetime: { type: Date }, // enterdatetime datetime
  version: { type: String }, // version varchar(255)
  status: { type: String }, // status varchar(255)
  releasedate: { type: Date }, // releasedate date
  approved: { type: String }, // approved varchar(20)
  cabourcharges: { type: Number }, // cabourcharges float
  cabourremark: { type: String }, // cabourremark varchar(255)
  overheadcharges: { type: Number }, // overheadcharges float
  overheadremark: { type: String }, // overheadremark varchar(255)
  setupcharges: { type: Number }, // setupcharges float
  setupremark: { type: String }, // setupremark varchar(255)
  testingcharges: { type: Number }, // testingcharges float
  testingremark: { type: String }, // testingremark varchar(255)
  materialcharges: { type: Number }, // materialcharges float
  materialremark: { type: String }, // materialremark varchar(255)
  finalcharges: { type: Number }, // finalcharges float
  finalremark: { type: String }, // finalremark varchar(255)
  itemname: { type: String }, // itemname varchar(20)
  remark: { type: String }, // remark varchar(255)
  alias1: { type: String }, // alias1 varchar(255)
  alias2: { type: String }, // alias2 varchar(255)
  itemType: { type: String }, // item_type varchar(255)
  category: { type: String }, // category varchar(255)
  categoryname: { type: String }, // categoryname varchar(25)
  modifiedby: { type: Number }, // modifiedby int(11)
  modifieddatetime: { type: Date }, // modifieddatetime datetime
  processid: { type: Number }, // processid int(11)
}, { timestamps: false })

export default mongoose.model('Bom', BomSchema, 'bom')
