import mongoose from 'mongoose'
const { Schema } = mongoose

const BookingtestSchema = new Schema({
  id: { type: Number }, // id int(11)
  testid: { type: Number }, // testid int(11)
  psrno: { type: String }, // psrno varchar(15)
  parentchild: { type: String }, // parentchild varchar(15)
  amount: { type: Number }, // amount float
  bid: { type: Number }, // bid int(11)
  discount: { type: Number }, // discount int(11)
  total: { type: Number }, // total float
  protocol: { type: String }, // protocol varchar(50)
  testname: { type: String }, // testname varchar(255)
  workingstandard: { type: String }, // workingstandard varchar(255)
  activevial: { type: String }, // activevial varchar(255)
  division: { type: String }, // division varchar(50)
  chemist: { type: Number }, // chemist int(11)
  descforworksheet: { type: String }, // descforworksheet varchar(50)
  result: { type: String }, // result varchar(500)
  units: { type: String }, // units varchar(50)
  desc1Limit1: { type: String }, // desc1/limit1 varchar(50)
  desc2Limit2: { type: String }, // desc2/limit2 varchar(50)
  limit3: { type: String }, // limit3 varchar(50)
  testdate: { type: Date }, // testdate date
  nabl: { type: String }, // nabl varchar(50)
  flag: { type: String }, // flag varchar(50)
  method: { type: String }, // method varchar(255)
  logic: { type: String }, // logic varchar(50)
  minlimit: { type: String }, // minlimit text
  maxlimit: { type: String }, // maxlimit text
  condition: { type: String }, // condition varchar(50)
  formula: { type: String }, // formula varchar(50)
  testtime: { type: String }, // testtime varchar(50)
  result2: { type: String }, // result2 varchar(50)
  result3: { type: String }, // result3 varchar(50)
  limit: { type: Number }, // limit float
  labelclaim: { type: String }, // labelclaim text
  peroflabelclaim: { type: String }, // peroflabelclaim varchar(200)
  pname: { type: String }, // pname varchar(255)
  parent: { type: String }, // parent varchar(255)
  description: { type: String }, // description text
  nacontent: { type: String }, // nacontent varchar(255)
  finalcontent: { type: String }, // finalcontent varchar(255)
  mean: { type: String }, // mean varchar(25)
  approved: { type: String }, // approved varchar(15)
  qty: { type: Number }, // qty int(20)
  datas: { type: String }, // datas text
  elogbook: { type: String }, // elogbook text
  resultdate: { type: Date }, // resultdate date
  testdatetime: { type: Date }, // testdatetime datetime
  resultsentence: { type: String }, // resultsentence longtext
  resultjson: { type: String }, // resultjson longtext
  approvedby: { type: Number }, // approvedby int(11)
  approveddatetime: { type: Date }, // approveddatetime datetime
  roaformat: { type: String }, // roaformat varchar(25)
  backweight: { type: Number }, // backweight float
  bypass: { type: String }, // bypass varchar(25)
  resultlablecalm: { type: Number }, // resultlablecalm decimal(15
  assigndatetime: { type: Date }, // assigndatetime datetime
  labelclaimunit: { type: String }, // labelclaimunit varchar(50)
  expanded: { type: String }, // expanded varchar(255)
  tid: { type: Number }, // tid int(11)
  rawdata: { type: Number }, // rawdata int(11)
  rawdatatemplate: { type: String }, // rawdatatemplate text
  startdate: { type: Date }, // startdate datetime
  enddate: { type: Date }, // enddate datetime
  formulaid: { type: Number }, // formulaid int(11)
  formuladata: { type: String }, // formuladata text
  testtypeid: { type: Number }, // testtypeid int(11)
  deatils: { type: String }, // deatils longtext
  noofstandard: { type: String }, // noofstandard longtext
  nooftest: { type: String }, // nooftest longtext
  impurities: { type: String }, // impurities longtext
  drugname: { type: String }, // drugname longtext
  hours: { type: Number }, // hours int(11)
  expecteddate: { type: Date }, // expecteddate date
  typemasterid: { type: Number }, // typemasterid int(11)
  drugminlimit2: { type: String }, // drugminlimit2 varchar(255)
  drugmaxlimit2: { type: String }, // drugmaxlimit2 varchar(255)
  impurityminlimit2: { type: String }, // impurityminlimit2 varchar(255)
  impuritymaxlimit2: { type: String }, // impuritymaxlimit2 varchar(255)
  parentChild: { type: Number }, // parent_child float
  versionno: { type: Number }, // versionno int(11)
  starttme: { type: Date }, // starttme datetime
  endtme: { type: Date }, // endtme datetime
  instrumenttype: { type: Number }, // instrumenttype int(11)
  departmentid: { type: Number }, // departmentid int(11)
  monograph: { type: String }, // monograph varchar(200)
  resultcheck: { type: Number }, // resultcheck int(11)
  printcoa: { type: String }, // printcoa varchar(10)
  overdueremarks: { type: String }, // overdueremarks varchar(255)
  monograph2: { type: String }, // monograph2 varchar(255)
  monograph3: { type: String }, // monograph3 varchar(255)
  monograph4: { type: String }, // monograph4 varchar(255)
  monograph5: { type: String }, // monograph5 varchar(255)
  rejectremarks: { type: String }, // rejectremarks varchar(255)
  prioritydays: { type: String }, // prioritydays varchar(10)
  prioritydate: { type: Date }, // prioritydate date
  priority: { type: String }, // priority varchar(10)
  approved2: { type: String }, // approved2 varchar(10)
  approvedby2: { type: Number }, // approvedby2 int(11)
  approveddatetime2: { type: Date }, // approveddatetime2 datetime
  bookingremarks: { type: String }, // bookingremarks varchar(255)
  chemicaltype: { type: String }, // chemicaltype varchar(50)
  investigationremarks: { type: String }, // investigationremarks text
  correctiveactiontakenremarks: { type: String }, // correctiveactiontakenremarks text
}, { timestamps: false })

export default mongoose.model('Bookingtest', BookingtestSchema, 'bookingtest')
