import mongoose from 'mongoose'
const { Schema } = mongoose

const Bookings1Schema = new Schema({
  id: { type: Number }, // id int(11)
  receiptdate: { type: Date }, // receiptdate date
  bookingno: { type: String }, // bookingno varchar(50)
  salsrno: { type: Number }, // salsrno int(11)
  clientname: { type: String }, // clientname varchar(100)
  cid: { type: Number }, // cid int(11)
  producttype: { type: String }, // producttype varchar(25)
  pid: { type: String }, // pid text
  billingdate: { type: Date }, // billingdate date
  brandname: { type: String }, // brandname varchar(255)
  genricname: { type: String }, // genricname varchar(255)
  samplecode: { type: String }, // samplecode varchar(255)
  sampledesc: { type: String }, // sampledesc text
  refno: { type: String }, // refno varchar(255)
  cancel: { type: String }, // cancel varchar(255)
  cancelremarks: { type: String }, // cancelremarks text
  isreportdispatched: { type: String }, // isreportdispatched varchar(250)
  dispatcheddatetime: { type: Date }, // dispatcheddatetime datetime
  dispatchedmode: { type: String }, // dispatchedmode varchar(255)
  dispatcheddetails: { type: String }, // dispatcheddetails text
  manufacturer: { type: String }, // manufacturer varchar(255)
  samplingdatefrom: { type: Date }, // samplingdatefrom date
  samplingdateto: { type: Date }, // samplingdateto date
  billno: { type: String }, // billno varchar(20)
  billingmode: { type: String }, // billingmode varchar(255)
  projectname: { type: String }, // projectname varchar(255)
  mfglicno: { type: String }, // mfglicno varchar(255)
  grade: { type: String }, // grade varchar(25)
  tentativereldate: { type: Date }, // tentativereldate date
  batchno: { type: String }, // batchno varchar(255)
  packsize: { type: String }, // packsize varchar(255)
  dformate: { type: String }, // dformate varchar(255)
  mfgdate: { type: Date }, // mfgdate date
  expdate: { type: Date }, // expdate date
  reqqty: { type: String }, // reqqty varchar(50)
  sampleqty: { type: String }, // sampleqty varchar(255)
  samplelocation: { type: String }, // samplelocation varchar(255)
  samplepacking: { type: String }, // samplepacking varchar(50)
  sampletype: { type: String }, // sampletype varchar(255)
  samplereceivedthrough: { type: String }, // samplereceivedthrough varchar(255)
  chemist: { type: Number }, // chemist int(11)
  samplecondition: { type: String }, // samplecondition varchar(255)
  remarks: { type: String }, // remarks text
  typeField: { type: String }, // type varchar(255)
  status: { type: String }, // status varchar(255)
  bookingparty: { type: String }, // bookingparty varchar(100)
  group: { type: String }, // group varchar(50)
  contactperson: { type: String }, // contactperson varchar(60)
  balance: { type: Number }, // balance float
  crno: { type: String }, // crno varchar(50)
  batchsize: { type: String }, // batchsize varchar(25)
  invoicenumber: { type: String }, // invoicenumber varchar(11)
  bookingsorderdate: { type: Date }, // bookingsorderdate date
  reportno: { type: String }, // reportno varchar(50)
  supplier: { type: String }, // supplier varchar(100)
  limit: { type: String }, // Limit varchar(255)
  labelclaim: { type: String }, // Labelclaim varchar(255)
  peroflabelclaim: { type: String }, // perofLabelclaim varchar(255)
  result: { type: String }, // result varchar(255)
  reldate: { type: Date }, // reldate date
  salesid: { type: Number }, // salesid int(11)
  notes: { type: String }, // notes text
  graph: { type: String }, // graph text
  signature: { type: String }, // signature varchar(25)
  reporttype: { type: String }, // reporttype varchar(10)
  listoftest: { type: String }, // listoftest varchar(512)
  productname: { type: String }, // productname varchar(255)
  pharmacopiea: { type: String }, // pharmacopiea varchar(50)
  print: { type: Number }, // print int(11)
  roaprint: { type: Number }, // roaprint int(11)
  sampledrawnby: { type: String }, // sampledrawnby text
  verifiedby: { type: String }, // verifiedby varchar(10)
  coaprint: { type: Number }, // coaprint int(11)
  printcoadate: { type: Date }, // printcoadate date
  block: { type: String }, // block varchar(15)
  nablscope: { type: String }, // nablscope varchar(15)
  mfgnans: { type: String }, // mfgnans varchar(20)
  dformatenans: { type: String }, // dformatenans varchar(20)
  gradenans: { type: String }, // gradenans varchar(20)
  projectnamenans: { type: String }, // projectnamenans varchar(20)
  expnans: { type: String }, // expnans varchar(50)
  samplingnansfrom: { type: String }, // samplingnansfrom varchar(50)
  samplingnansto: { type: String }, // samplingnansto varchar(50)
  balanceweight: { type: Number }, // balanceweight float
  data1: { type: String }, // data1 varchar(512)
  data2: { type: String }, // data2 varchar(512)
  nablno: { type: String }, // nablno varchar(25)
  nablnopf: { type: String }, // nablnopf varchar(10)
  enterby: { type: Number }, // enterby int(11)
  enterdatetime: { type: Date }, // enterdatetime datetime
  modifiedby: { type: Number }, // modifiedby int(11)
  modifieddatetime: { type: Date }, // modifieddatetime datetime
  sampleconditionyesno: { type: String }, // sampleconditionyesno varchar(25)
  priority: { type: String }, // priority varchar(255)
  coareldate: { type: Date }, // coareldate date
  company: { type: Number }, // company int(11)
  discipline: { type: String }, // discipline varchar(20)
  statementofconformity: { type: String }, // statementofconformity varchar(30)
  listofchemist: { type: String }, // listofchemist varchar(255)
  filelocation: { type: String }, // filelocation varchar(50)
  samplefiles: { type: String }, // samplefiles varchar(255)
  dispatchedby: { type: Number }, // dispatchedby int(11)
  environmental: { type: String }, // environmental varchar(100)
  stability: { type: Number }, // stability int(11)
  approvedby: { type: Number }, // approvedby int(11)
  approveddatetime: { type: Date }, // approveddatetime datetime
  testreviewby: { type: Number }, // testreviewby int(11)
  testreviewdatetime: { type: Date }, // testreviewdatetime datetime
  approved: { type: String }, // approved varchar(10)
  testreview: { type: String }, // testreview varchar(50)
  allottedby: { type: Number }, // allottedby int(11)
  allottedbydatetime: { type: Date }, // allottedbydatetime datetime
  approvedrejectremarks: { type: String }, // approvedrejectremarks varchar(255)
  reviewrejectremarks: { type: String }, // reviewrejectremarks varchar(255)
  generalremarks: { type: String }, // generalremarks varchar(255)
  versionremarks: { type: String }, // versionremarks varchar(255)
  editcoa: { type: String }, // editcoa varchar(10)
  printremarks: { type: String }, // printremarks varchar(255)
  roaversion: { type: Number }, // roaversion int(11)
  coaversion: { type: Number }, // coaversion int(11)
  bookingversion: { type: Number }, // bookingversion int(11)
  testreviewbyremarks: { type: String }, // testreviewbyremarks varchar(255)
  entrymail: { type: String }, // entrymail varchar(10)
  roamail: { type: String }, // roamail varchar(10)
  coamail: { type: String }, // coamail varchar(10)
  version: { type: Number }, // version int(11)
  bookingurl: { type: String }, // bookingurl varchar(255)
  testreviewremarks: { type: String }, // testreviewremarks varchar(255)
  bookingroaurl: { type: String }, // bookingroaurl varchar(255)
  retentionqty: { type: Number }, // retentionqty int(11)
  retentioncompletiondate: { type: Date }, // retentioncompletiondate date
  retentiondate: { type: Date }, // retentiondate date
  retentiondestructiondate: { type: Date }, // retentiondestructiondate date
  retentionunit: { type: Number }, // retentionunit int(11)
  additionalremarks: { type: String }, // additionalremarks text
  remark: { type: String }, // remark varchar(50)
}, { timestamps: false })

export default mongoose.model('Bookings1', Bookings1Schema, 'bookings1')
