import mongoose from 'mongoose'
const { Schema } = mongoose

const BookingsitemSchema = new Schema({
  typeField: { type: String }, // TYPE varchar(2)
  bno: { type: String }, // BNO varchar(9)
  bdate: { type: String }, // BDATE varchar(10)
  pcode: { type: Number }, // PCODE int(11)
  code: { type: Number }, // CODE int(11)
  disc: { type: Number }, // DISC int(11)
  item: { type: String }, // ITEM varchar(72)
  qty: { type: Number }, // QTY int(11)
  rate: { type: Number }, // RATE decimal(7
  unit: { type: String }, // UNIT varchar(10)
  batchNo: { type: String }, // BATCH_NO varchar(20)
  netamt: { type: Number }, // NETAMT decimal(7
  station: { type: String }, // STATION varchar(25)
  stat: { type: String }, // STAT varchar(20)
  srNo: { type: Number }, // SR_NO int(11)
  netamt1: { type: Number }, // NETAMT1 int(11)
  pack: { type: String }, // PACK varchar(10)
  mDate: { type: String }, // M_DATE varchar(10)
  slid: { type: String }, // SLID varchar(9)
  crno: { type: String }, // CRNO varchar(16)
  amount: { type: Number }, // AMOUNT int(11)
  dis: { type: Number }, // DIS int(11)
  username: { type: String }, // USERNAME varchar(10)
  fbdate: { type: String }, // FBDATE varchar(10)
  tbdate: { type: String }, // TBDATE varchar(10)
  tax: { type: Number }, // TAX int(11)
  taxamt: { type: Number }, // TAXAMT int(11)
  scode: { type: Number }, // SCODE int(11)
  amount1: { type: Number }, // AMOUNT1 int(11)
  disamt: { type: Number }, // DISAMT int(11)
  bcode: { type: Number }, // BCODE int(11)
  refNo: { type: String }, // REF_NO varchar(20)
  saletype: { type: String }, // SALETYPE varchar(10)
  gtype: { type: String }, // GTYPE varchar(10)
  gcode: { type: Number }, // GCODE int(11)
  ptycode: { type: Number }, // PTYCODE int(11)
  ptyname: { type: String }, // PTYNAME varchar(10)
  cnarr: { type: String }, // CNARR varchar(10)
  testReq: { type: String }, // TEST_REQ varchar(10)
  marking: { type: String }, // MARKING varchar(10)
  id: { type: Number }, // id int(11)
}, { timestamps: false })

export default mongoose.model('Bookingsitem', BookingsitemSchema, 'bookingsitem')
