import mongoose from 'mongoose'
const { Schema } = mongoose

const BranchmasterSchema = new Schema({
  id: { type: Number }, // id int(11)
  name: { type: String }, // name varchar(255)
  companyname: { type: String }, // companyname varchar(255)
  branchtype: { type: String }, // branchtype varchar(255)
  code: { type: String }, // code varchar(255)
  officeno: { type: String }, // officeno varchar(255)
  complexname: { type: String }, // complexname varchar(255)
  streetname: { type: String }, // streetname varchar(255)
  landmark: { type: String }, // landmark varchar(255)
  area: { type: String }, // area varchar(255)
  city: { type: String }, // city varchar(255)
  state: { type: String }, // state varchar(255)
  country: { type: String }, // country varchar(255)
  pincode: { type: String }, // pincode varchar(255)
  phone: { type: String }, // phone varchar(255)
  fax: { type: String }, // fax varchar(255)
  mobile: { type: String }, // mobile varchar(255)
  email: { type: String }, // email varchar(255)
  website: { type: String }, // website varchar(255)
  panno: { type: String }, // panno varchar(255)
  taxidentificationno: { type: String }, // taxidentificationno varchar(255)
  servicetaxno: { type: String }, // servicetaxno varchar(255)
  vatno: { type: String }, // vatno varchar(255)
  tdsno: { type: String }, // tdsno varchar(255)
  companyregno: { type: String }, // companyregno varchar(255)
  importexportcode: { type: String }, // importexportcode varchar(255)
  exportpromotioncapitalcode: { type: String }, // exportpromotioncapitalcode varchar(255)
  employeestateinsurancecode: { type: String }, // employeestateinsurancecode varchar(255)
  establishyear: { type: String }, // establishyear varchar(25)
  professionaltax: { type: String }, // professionaltax varchar(255)
  providendfundcode: { type: String }, // providendfundcode varchar(255)
  centralsalestax: { type: String }, // centralsalestax varchar(255)
  excisecontrolcode: { type: String }, // excisecontrolcode varchar(255)
  nagarpalikanigamlicenceno: { type: String }, // nagarpalikanigamlicenceno varchar(255)
  otherno: { type: String }, // otherno varchar(255)
  deleteField: { type: Number }, // delete int(11)
  active: { type: Number }, // active int(11)
  company: { type: Number }, // company int(11)
  enterby: { type: Number }, // enterby int(11)
  modifiedby: { type: Number }, // modifiedby int(11)
  dlno: { type: String }, // dlno varchar(50)
  modifieddatetime: { type: Date }, // modifieddatetime datetime
  enterdatetime: { type: Date }, // enterdatetime datetime
  action: { type: Number }, // action int(11)
  brand: { type: String }, // brand varchar(50)
  shortcode: { type: String }, // shortcode varchar(50)
  gstno: { type: String }, // gstno varchar(50)
  dlno2: { type: String }, // dlno2 varchar(50)
  gstusername: { type: String }, // gstusername varchar(50)
  gstpassword: { type: String }, // gstpassword varchar(50)
  ewayusername: { type: String }, // ewayusername varchar(50)
  ewaypassword: { type: String }, // ewaypassword varchar(50)
  einvoiceusername: { type: String }, // einvoiceusername varchar(50)
  einvoicepassword: { type: String }, // einvoicepassword varchar(50)
  branch: { type: Number }, // branch int(11)
}, { timestamps: false })

export default mongoose.model('Branchmaster', BranchmasterSchema, 'branchmaster')
