import mongoose from 'mongoose'
const { Schema } = mongoose

const CompanymasterSchema = new Schema({
  id: { type: Number }, // id int(11)
  name: { type: String }, // name varchar(255)
  address: { type: String }, // address varchar(255)
  city: { type: String }, // city varchar(25)
  state: { type: String }, // state varchar(25)
  country: { type: String }, // country varchar(25)
  pincode: { type: String }, // pincode varchar(11)
  financialyear: { type: Date }, // financialyear date
  vatno: { type: String }, // vatno varchar(25)
  tinno: { type: String }, // tinno varchar(25)
  panno: { type: String }, // panno varchar(25)
  servicetaxno: { type: String }, // servicetaxno varchar(25)
  phone: { type: String }, // phone varchar(25)
  email: { type: String }, // email varchar(50)
  website: { type: String }, // website varchar(50)
  deleteField: { type: Number }, // delete int(11)
  active: { type: Number }, // active int(11)
  gstno: { type: String }, // gstno varchar(25)
  code: { type: String }, // code varchar(15)
  analyticallicno: { type: Number }, // analyticallicno int(11)
  landmark: { type: String }, // landmark varchar(100)
  company: { type: Number }, // company int(11)
  aumusername: { type: String }, // aumusername varchar(20)
  aumpassword: { type: String }, // aumpassword varchar(20)
  gspusername: { type: String }, // gspusername varchar(25)
  gsppassword: { type: String }, // gsppassword varchar(25)
  area: { type: String }, // area varchar(50)
  logo: { type: String }, // logo varchar(100)
  color: { type: String }, // color varchar(100)
  host: { type: String }, // host varchar(50)
  port: { type: String }, // port varchar(50)
  isssl: { type: String }, // isssl varchar(50)
  istls: { type: String }, // istls varchar(50)
  username: { type: String }, // username varchar(50)
  password: { type: String }, // password varchar(50)
  fromaddress: { type: String }, // fromaddress varchar(50)
  fromname: { type: String }, // fromname varchar(50)
  url: { type: String }, // url varchar(50)
  apikey: { type: String }, // apikey varchar(50)
  apisecret: { type: String }, // apisecret varchar(50)
  senderid: { type: String }, // senderid varchar(50)
  providername: { type: String }, // providername varchar(50)
  templateid: { type: String }, // templateid varchar(50)
  near: { type: String }, // near varchar(50)
  header: { type: String }, // header varchar(100)
  footer: { type: String }, // footer varchar(100)
  favicon: { type: String }, // favicon varchar(100)
  letterhead: { type: String }, // letterhead varchar(100)
  accountname: { type: String }, // accountname varchar(100)
  accounttype: { type: String }, // accounttype varchar(100)
  accno: { type: String }, // accno varchar(100)
  micrcode: { type: String }, // micrcode varchar(100)
  rtgs: { type: String }, // rtgs varchar(100)
  swiftcode: { type: String }, // swiftcode varchar(100)
  branchaddress: { type: String }, // branchaddress varchar(100)
  registeraddress: { type: String }, // registeraddress varchar(100)
  terms: { type: String }, // terms text
  bankname: { type: String }, // bankname varchar(100)
  msmeno: { type: String }, // msmeno varchar(100)
  saccode: { type: String }, // saccode varchar(100)
}, { timestamps: false })

export default mongoose.model('Companymaster', CompanymasterSchema, 'companymaster')
