import mongoose from 'mongoose'
const { Schema } = mongoose

const ItemmasterSchema = new Schema({
  id: { type: Number }, // id int(11)
  name: { type: String }, // name varchar(255)
  size: { type: String }, // size varchar(255)
  category: { type: String }, // category varchar(255)
  subcategory: { type: String }, // subcategory varchar(255)
  remarks: { type: String }, // remarks varchar(255)
  minQty: { type: Number }, // min_qty int(11)
  reorderQty: { type: Number }, // reorder_qty int(11)
  barcode: { type: String }, // barcode varchar(255)
  cgst: { type: Number }, // cgst float
  sgst: { type: Number }, // sgst float
  igst: { type: Number }, // igst int(11)
  cess: { type: Number }, // cess int(11)
  hsncode: { type: String }, // hsncode varchar(255)
  briefDescription: { type: String }, // brief_description text
  openingqty: { type: Number }, // openingqty float
  purchaseAccount: { type: Number }, // purchase_account int(11)
  salesAccount: { type: Number }, // sales_account int(11)
  purchaseRate: { type: Number }, // purchase_rate float
  salesRate: { type: Number }, // sales_rate float
  machineName: { type: String }, // machine_name varchar(255)
  mrp: { type: Number }, // mrp float
  detailedDescription: { type: String }, // detailed_description text
  technicalSpecification: { type: String }, // technical_specification text
  active2: { type: String }, // active2 enum('Yes'
  itemType: { type: String }, // item_type varchar(50)
  manufacturer: { type: String }, // manufacturer varchar(100)
  company: { type: Number }, // company int(11)
  deleteField: { type: Number }, // delete int(11)
  lock: { type: Number }, // lock int(11)
  enterby: { type: Number }, // enterby int(11)
  enterdatetime: { type: Date }, // enterdatetime datetime
  modifiedby: { type: Number }, // modifiedby int(11)
  modifieddatetime: { type: Date }, // modifieddatetime datetime
  active: { type: Number }, // active int(11)
  branch: { type: Number }, // branch int(11)
  action: { type: String }, // action varchar(25)
  defaultField: { type: String }, // default varchar(10)
  views: { type: Number }, // views int(11)
  name2: { type: Number }, // name2 int(11)
  qc: { type: String }, // qc varchar(20)
  qcin: { type: String }, // qcin varchar(20)
  sheetNo: { type: String }, // sheet_no varchar(255)
  moc: { type: String }, // moc varchar(255)
  uom: { type: String }, // uom varchar(255)
  comment: { type: String }, // comment varchar(255)
  designator: { type: String }, // designator varchar(255)
  footprint: { type: String }, // footprint varchar(255)
  libref: { type: String }, // libref varchar(255)
  designation: { type: String }, // designation varchar(255)
  supplierRef: { type: String }, // supplier_ref varchar(255)
  flag: { type: Number }, // flag int(11)
  unit: { type: String }, // unit varchar(25)
  casno: { type: String }, // casno varchar(255)
  makeBrand: { type: String }, // make_brand varchar(255)
  alias1: { type: String }, // alias1 varchar(255)
  alias2: { type: String }, // alias2 varchar(255)
  alias3: { type: String }, // alias3 varchar(255)
  alias4: { type: String }, // alias4 varchar(255)
  alias5: { type: String }, // alias5 varchar(255)
  alias6: { type: String }, // alias6 varchar(255)
  printname: { type: String }, // printname varchar(255)
  qcsampleqty: { type: Number }, // qcsampleqty float
  qccontrolqty: { type: Number }, // qccontrolqty float
  marketunit: { type: String }, // marketunit varchar(100)
  conversionfactor: { type: String }, // conversionfactor varchar(50)
  stockyesno: { type: String }, // stockyesno varchar(20)
  whereused: { type: String }, // whereused varchar(50)
  tally1: { type: String }, // tally1 varchar(150)
  tally2: { type: String }, // tally2 varchar(150)
  tally3: { type: String }, // tally3 varchar(150)
  tally4: { type: String }, // tally4 varchar(150)
  technicaldocuments: { type: String }, // technicaldocuments varchar(255)
  categoryvalue: { type: String }, // categoryvalue varchar(50)
  subcategoryvalue: { type: String }, // subcategoryvalue varchar(50)
  productioncode: { type: String }, // productioncode varchar(255)
  importtype: { type: String }, // importtype varchar(20)
  productionrate: { type: Number }, // productionrate decimal(15
  pricelist: { type: String }, // pricelist text
  targetcategory: { type: Number }, // targetcategory int(11)
  components: { type: String }, // components varchar(255)
  batchnooption: { type: String }, // batchnooption varchar(255)
  batchnotype: { type: String }, // batchnotype varchar(10)
  batchnopattern: { type: Number }, // batchnopattern int(11)
  parameter1: { type: String }, // parameter1 varchar(10)
  parameter2: { type: String }, // parameter2 varchar(25)
  parameter3: { type: String }, // parameter3 varchar(25)
  csv: { type: String }, // csv varchar(10)
  bomexpectedqty: { type: String }, // bomexpectedqty varchar(25)
  att1: { type: String }, // att1 varchar(255)
  att2: { type: String }, // att2 varchar(255)
  image1: { type: String }, // image1 varchar(200)
  image2: { type: String }, // image2 varchar(200)
  image3: { type: String }, // image3 varchar(200)
  image4: { type: String }, // image4 varchar(200)
  latestproduct: { type: String }, // latestproduct varchar(10)
  features: { type: String }, // features text
  offer: { type: String }, // offer varchar(20)
  itemType2: { type: String }, // item_type2 varchar(20)
  slabwiserateMinqty: { type: Number }, // slabwiserate_minqty decimal(15
  slabwiserateMaxqty: { type: Number }, // slabwiserate_maxqty decimal(15
  points: { type: Number }, // points float
  bomcostingtype: { type: String }, // bomcostingtype varchar(15)
  showinmobile: { type: String }, // showinmobile varchar(3)
  fgitem: { type: String }, // fgitem varchar(255)
  fgproduct: { type: String }, // fgproduct varchar(50)
  offerlink: { type: String }, // offerlink varchar(100)
  purchaseactive: { type: Number }, // purchaseactive int(11)
  typeField: { type: String }, // type varchar(50)
  column109: { type: Number }, // Column 109 int(11)
  header: { type: String }, // header varchar(255)
  typeofcolumn: { type: String }, // typeofcolumn varchar(50)
  date: { type: Date }, // date date
  dimensions: { type: String }, // dimensions varchar(255)
  make: { type: String }, // make varchar(100)
  model: { type: String }, // model varchar(100)
  columnid: { type: String }, // columnid varchar(50)
  dateofperformanc: { type: Date }, // dateofperformanc date
  performby: { type: String }, // performby varchar(50)
  status: { type: String }, // status varchar(50)
  issuedto: { type: String }, // issuedto varchar(100)
  dateissuance: { type: Date }, // dateissuance date
  checkedby: { type: String }, // checkedby varchar(100)
  injections: { type: String }, // injections varchar(100)
  serialno: { type: String }, // serialno varchar(100)
  lotNo: { type: String }, // lot_no varchar(100)
  formula: { type: String }, // formula varchar(100)
  molWeight: { type: String }, // mol_weight varchar(100)
  effectiveDate: { type: Date }, // effective_date date
  validUpTo: { type: String }, // valid_up_to varchar(100)
  image: { type: String }, // image varchar(200)
  workingstanderno: { type: String }, // workingstanderno varchar(100)
  instructions: { type: String }, // instructions varchar(100)
  srno: { type: String }, // srno varchar(100)
  comapnyname: { type: String }, // comapnyname varchar(50)
  potency: { type: String }, // potency varchar(50)
  storagecondition: { type: String }, // storagecondition varchar(100)
  assaypotency: { type: String }, // assaypotency varchar(100)
  stdreceivingdate: { type: Date }, // stdreceivingdate date
  lodwater: { type: String }, // lodwater varchar(100)
  mfgdate: { type: Date }, // mfgdate date
  expdate: { type: Date }, // expdate date
  stock: { type: String }, // stock varchar(100)
  currentvial: { type: String }, // currentvial varchar(50)
  documentsatisfactory: { type: String }, // documentsatisfactory varchar(100)
  received: { type: String }, // received varchar(50)
  acceptedby: { type: String }, // acceptedby varchar(50)
  catalogueno: { type: String }, // catalogueno varchar(100)
  casenumber: { type: String }, // casenumber varchar(100)
  code: { type: String }, // code varchar(255)
  grade: { type: String }, // grade varchar(50)
  instock: { type: String }, // instock varchar(50)
  tValue: { type: Number }, // t_value int(11)
  type2: { type: String }, // type2 varchar(50)
  guid: { type: String }, // guid varchar(50)
  refrencestandard: { type: String }, // refrencestandard varchar(50)
  refrencestandardid: { type: Number }, // refrencestandardid int(11)
  workingstdfd: { type: String }, // workingstdfd varchar(50)
  workingstdspecification: { type: String }, // workingstdspecification varchar(50)
  assay: { type: String }, // assay varchar(50)
  batchno: { type: String }, // batchno varchar(50)
  opendate: { type: Date }, // opendate datetime
  validuptodate: { type: Date }, // validuptodate datetime
  coapresent: { type: Number }, // coapresent int(11)
  receivedby: { type: String }, // receivedby varchar(50)
  authorizedby: { type: Number }, // authorizedby int(11)
  godown: { type: Number }, // godown int(11)
  comapnyid: { type: Number }, // comapnyid int(11)
  stockvial: { type: Number }, // stockvial float
  balancevialqty: { type: Number }, // balancevialqty int(11)
  refid: { type: String }, // refid varchar(50)
}, { timestamps: false })

export default mongoose.model('Itemmaster', ItemmasterSchema, 'itemmaster')
