import mongoose from 'mongoose'
const { Schema } = mongoose

const MsaleSchema = new Schema({
  typeField: { type: String }, // TYPE varchar(1)
  bno: { type: String }, // BNO varchar(15)
  bdate: { type: String }, // BDATE varchar(10)
  pcode: { type: String }, // PCODE varchar(13)
  code: { type: String }, // CODE varchar(12)
  disc: { type: String }, // DISC varchar(7)
  item: { type: String }, // ITEM varchar(56)
  qty: { type: String }, // QTY varchar(8)
  rate: { type: String }, // RATE varchar(13)
  unit: { type: String }, // UNIT varchar(10)
  batchNo: { type: String }, // BATCH_NO varchar(20)
  netamt: { type: String }, // NETAMT varchar(13)
  station: { type: String }, // STATION varchar(25)
  stat: { type: String }, // STAT varchar(16)
  srNo: { type: Number }, // SR_NO int(11)
  netamt1: { type: String }, // NETAMT1 varchar(7)
  pack: { type: String }, // PACK varchar(10)
  mDate: { type: String }, // M_DATE varchar(10)
  slid: { type: String }, // SLID varchar(10)
  crno: { type: String }, // CRNO varchar(20)
  amount: { type: String }, // AMOUNT varchar(7)
  dis: { type: String }, // DIS varchar(7)
  username: { type: String }, // USERNAME varchar(10)
  fbdate: { type: String }, // FBDATE varchar(10)
  tbdate: { type: String }, // TBDATE varchar(10)
  tax: { type: String }, // TAX varchar(7)
  taxamt: { type: String }, // TAXAMT varchar(7)
  scode: { type: Number }, // SCODE int(11)
  amount1: { type: String }, // AMOUNT1 varchar(7)
  disamt: { type: String }, // DISAMT varchar(7)
  bcode: { type: String }, // BCODE varchar(7)
  refNo: { type: String }, // REF_NO varchar(16)
  saletype: { type: String }, // SALETYPE varchar(10)
  gtype: { type: String }, // GTYPE varchar(10)
  gcode: { type: String }, // GCODE varchar(7)
  ptycode: { type: String }, // PTYCODE varchar(7)
  ptyname: { type: String }, // PTYNAME varchar(10)
  cnarr: { type: String }, // CNARR varchar(10)
  testReq: { type: String }, // TEST_REQ varchar(10)
  marking: { type: String }, // MARKING varchar(10)
  id: { type: Number }, // id int(11)
}, { timestamps: false })

export default mongoose.model('Msale', MsaleSchema, 'msale')
