import mongoose from 'mongoose'
const { Schema } = mongoose

const OthersalesSchema = new Schema({
  id: { type: Number }, // id int(11)
  salesorderdate: { type: Date }, // salesorderdate date
  invoicedate: { type: Date }, // invoicedate date
  invoicenumber: { type: String }, // invoicenumber varchar(255)
  client: { type: String }, // client varchar(255)
  remark: { type: String }, // remark varchar(255)
  account: { type: String }, // account varchar(12)
  typeField: { type: String }, // type varchar(25)
  status: { type: String }, // status varchar(25)
  notes: { type: String }, // notes text
  vouchertype: { type: String }, // vouchertype varchar(25)
  voucherno: { type: String }, // voucherno varchar(25)
  gross: { type: Number }, // gross float
  discount: { type: Number }, // discount float
  servicetax: { type: Number }, // servicetax float
  educess: { type: Number }, // educess float
  hscs: { type: Number }, // hscs float
  roundoff: { type: Number }, // roundoff float
  total: { type: Number }, // total float
  gtotal: { type: Number }, // gtotal float
  deliverydatetime: { type: Date }, // deliverydatetime datetime
  currency: { type: Number }, // currency int(11)
  startdate: { type: Date }, // startdate date
  enddate: { type: Date }, // enddate date
  discountper: { type: Number }, // discountper float
  sbctax: { type: Number }, // sbctax float
  kkctax: { type: Number }, // kkctax float
  freight: { type: Number }, // freight float
  cgstfreight: { type: Number }, // cgstfreight decimal(15
  sgstfreight: { type: Number }, // sgstfreight decimal(15
  igstfreight: { type: Number }, // igstfreight decimal(15
  pono: { type: String }, // pono varchar(50)
  podate: { type: Date }, // podate date
  sampledate: { type: Date }, // sampledate datetime
  isduplicate: { type: String }, // isduplicate varchar(10)
  servicetaxper: { type: Number }, // servicetaxper float
  sbctaxper: { type: Number }, // sbctaxper float
  kkctaxper: { type: Number }, // kkctaxper float
  billingdatefrom: { type: Date }, // billingdatefrom date
  billingdateto: { type: Date }, // billingdateto date
  cgst: { type: Number }, // cgst float
  sgst: { type: Number }, // sgst float
  igst: { type: Number }, // igst float
  gst: { type: Number }, // gst int(11)
  printtype: { type: String }, // printtype varchar(25)
  paymentterms: { type: String }, // paymentterms varchar(50)
  placeofsupply: { type: String }, // placeofsupply varchar(150)
  statecode: { type: String }, // statecode varchar(25)
  cess: { type: Number }, // cess float
  company: { type: Number }, // company int(11)
  ackno: { type: String }, // AckNo varchar(255)
  ackdt: { type: String }, // AckDt varchar(255)
  irn: { type: String }, // Irn varchar(255)
  signedinvoice: { type: String }, // SignedInvoice text
  signedqrcode: { type: String }, // SignedQRCode text
  einvoiceStatus: { type: String }, // einvoice_Status varchar(255)
  ewbno: { type: String }, // EwbNo varchar(255)
  ewbdt: { type: String }, // EwbDt varchar(255)
  ewbvalidtill: { type: String }, // EwbValidTill varchar(255)
  couriercompany: { type: String }, // couriercompany varchar(255)
  couriergstno: { type: String }, // couriergstno varchar(255)
  distance: { type: String }, // distance varchar(255)
  vehno: { type: String }, // vehno varchar(255)
  vehtype: { type: String }, // vehtype varchar(255)
  courierdocket: { type: String }, // courierdocket varchar(255)
  transdocdate: { type: Date }, // transdocdate date
  transmode: { type: String }, // transmode varchar(255)
  clientpin: { type: Number }, // clientpin int(11)
  branchpin: { type: Number }, // branchpin int(11)
  ewaybill: { type: String }, // ewaybill varchar(20)
  branch: { type: Number }, // branch int(11)
  invoiceno: { type: String }, // invoiceno varchar(50)
  deleteField: { type: Number }, // delete int(11)
  active: { type: Number }, // active int(11)
  type2: { type: String }, // type2 varchar(50)
  billingaddress: { type: String }, // billingaddress varchar(50)
  guid: { type: String }, // guid varchar(100)
  enterby: { type: Number }, // enterby int(11)
  enterdatetime: { type: Date }, // enterdatetime datetime
  modifieddatetime: { type: Date }, // modifieddatetime datetime
  modifiedby: { type: Number }, // modifiedby int(11)
  shippingdate: { type: Date }, // shippingdate date
  orderby: { type: Number }, // orderby int(11)
  approved: { type: String }, // approved varchar(25)
  totalcgst: { type: Number }, // totalcgst float
  totalsgst: { type: Number }, // totalsgst float
  totaligst: { type: Number }, // totaligst float
  subtotal: { type: Number }, // subtotal float
  clientstate: { type: String }, // clientstate varchar(50)
  netfreight: { type: Number }, // netfreight decimal(15
  netpandf: { type: Number }, // netpandf decimal(15
  pandf: { type: Number }, // pandf decimal(15
  gstno: { type: String }, // gstno varchar(15)
  cgstperfreight: { type: Number }, // cgstperfreight float
  sgstperfreight: { type: Number }, // sgstperfreight float
  igstperfreight: { type: Number }, // igstperfreight float
  igstpandf: { type: Number }, // igstpandf decimal(15
  cgstpandf: { type: Number }, // cgstpandf decimal(15
  sgstpandf: { type: Number }, // sgstpandf decimal(15
}, { timestamps: false })

export default mongoose.model('Othersales', OthersalesSchema, 'othersales')
