import mongoose from 'mongoose'
const { Schema } = mongoose

const OtherpurchaseorderSchema = new Schema({
  id: { type: Number }, // id int(11)
  otherpurchaseorderdate: { type: Date }, // otherpurchaseorderdate date
  purchasenumber: { type: String }, // purchasenumber varchar(50)
  materialindentno: { type: Number }, // materialindentno int(11)
  supplier: { type: Number }, // supplier int(11)
  remark: { type: String }, // remark varchar(255)
  account: { type: String }, // account varchar(12)
  typeField: { type: String }, // type varchar(25)
  type1: { type: String }, // type1 varchar(25)
  invoicetype: { type: String }, // invoicetype varchar(25)
  status: { type: String }, // status varchar(25)
  notes: { type: String }, // notes text
  vouchertype: { type: String }, // vouchertype varchar(25)
  voucherno: { type: String }, // voucherno varchar(25)
  discount: { type: String }, // discount varchar(25)
  total: { type: String }, // total varchar(25)
  receiptdate: { type: Date }, // receiptdate date
  vatper: { type: Number }, // vatper float
  addvatper: { type: Number }, // addvatper float
  vat: { type: Number }, // vat float
  additionalVat: { type: Number }, // additional_vat float
  miscdisc: { type: Number }, // miscdisc int(11)
  otheremark: { type: String }, // otheremark varchar(255)
  purchase4: { type: String }, // purchase4 varchar(255)
  branch: { type: Number }, // branch int(11)
  gross: { type: Number }, // gross double
  manufacture: { type: String }, // manufacture varchar(100)
  roundoff: { type: String }, // roundoff varchar(25)
  suppliernodate: { type: String }, // suppliernodate varchar(255)
  tinno: { type: String }, // tinno varchar(255)
  servicetaxno: { type: String }, // servicetaxno varchar(255)
  narration: { type: String }, // narration varchar(255)
  rate: { type: String }, // rate varchar(255)
  otherremark: { type: String }, // otherremark varchar(255)
  other: { type: String }, // other varchar(255)
  gtotal: { type: String }, // gtotal varchar(100)
  maintotal: { type: Number }, // maintotal float
  company: { type: String }, // company varchar(255)
  shiptocompany: { type: Number }, // shiptocompany int(11)
  paymentterm: { type: String }, // paymentterm varchar(255)
  freight: { type: String }, // freight varchar(100)
  othercharges: { type: String }, // othercharges varchar(100)
  cst: { type: String }, // cst varchar(100)
  deleteField: { type: Number }, // delete int(11)
  lock: { type: Number }, // lock int(11)
  enterby: { type: Number }, // enterby int(11)
  enterdatetime: { type: Date }, // enterdatetime datetime
  modifiedby: { type: Number }, // modifiedby int(11)
  modifieddatetime: { type: Date }, // modifieddatetime datetime
  active: { type: Number }, // active int(11)
  action: { type: String }, // action varchar(25)
  shippingTerms: { type: String }, // shipping_terms varchar(15)
  shippingdate: { type: Date }, // shippingdate date
  shipping: { type: Number }, // shipping double
  district: { type: String }, // district varchar(25)
  approved: { type: String }, // approved varchar(25)
  postatus: { type: String }, // postatus varchar(25)
  authorizedperson: { type: String }, // authorizedperson varchar(255)
  supplieremail: { type: String }, // supplieremail varchar(255)
  suppliermobile: { type: String }, // suppliermobile varchar(15)
  orderby: { type: Number }, // orderby int(11)
  approvedby: { type: Number }, // approvedby int(11)
  totalqty: { type: String }, // totalqty varchar(25)
  receiveddate: { type: Date }, // receiveddate date
  grnno: { type: Number }, // grnno int(11)
  cstper: { type: Number }, // cstper float
  subtotal: { type: Number }, // subtotal float
  duedate: { type: Date }, // duedate date
  duedays: { type: Number }, // duedays int(11)
  pono: { type: String }, // pono varchar(50)
  supplierchallanno: { type: String }, // supplierchallanno varchar(50)
  challandate: { type: Date }, // challandate date
  godown: { type: String }, // godown varchar(255)
  transporter: { type: String }, // transporter varchar(255)
  truckno: { type: String }, // truckno varchar(50)
  lrno: { type: String }, // lrno varchar(50)
  addother: { type: Number }, // addother float
  category: { type: String }, // category varchar(50)
  tds: { type: Number }, // tds float
  addtds: { type: Number }, // addtds float
  purchasechallannumber: { type: String }, // purchasechallannumber varchar(50)
  paymentapproved: { type: String }, // paymentapproved varchar(25)
  file1: { type: String }, // file1 varchar(255)
  file2: { type: String }, // file2 varchar(255)
  file3: { type: String }, // file3 varchar(255)
  file4: { type: String }, // file4 varchar(255)
  file5: { type: String }, // file5 varchar(255)
  adjustment: { type: Number }, // adjustment double
  balance: { type: Number }, // balance float
  totalsgst: { type: Number }, // totalsgst float
  totalcgst: { type: Number }, // totalcgst float
  totaligst: { type: Number }, // totaligst float
  area: { type: String }, // area varchar(255)
  panfdisc: { type: Number }, // panfdisc float
  pandfamount: { type: Number }, // pandfamount float
  pandf: { type: Number }, // pandf float
  cgstperpandf: { type: Number }, // cgstperpandf float
  cgstpandf: { type: Number }, // cgstpandf float
  sgstperpandf: { type: Number }, // sgstperpandf float
  sgstpandf: { type: Number }, // sgstpandf float
  igstperpandf: { type: Number }, // igstperpandf float
  igstpandf: { type: Number }, // igstpandf float
  netpandf: { type: Number }, // netpandf float
  cgstperfreight: { type: Number }, // cgstperfreight float
  cgstfreight: { type: Number }, // cgstfreight float
  sgstperfreight: { type: Number }, // sgstperfreight float
  sgstfreight: { type: Number }, // sgstfreight float
  igstperfreight: { type: Number }, // igstperfreight float
  igstfreight: { type: Number }, // igstfreight float
  netfreight: { type: Number }, // netfreight float
  currency: { type: String }, // currency varchar(255)
  cgstperothercharges: { type: Number }, // cgstperothercharges float
  cgstothercharges: { type: Number }, // cgstothercharges float
  sgstperothercharges: { type: Number }, // sgstperothercharges float
  sgstothercharges: { type: Number }, // sgstothercharges float
  igstperothercharges: { type: Number }, // igstperothercharges float
  igstothercharges: { type: Number }, // igstothercharges float
  netothercharges: { type: Number }, // netothercharges float
  costcenter: { type: Number }, // costcenter int(11)
  billingaddress: { type: String }, // billingaddress text
  attachment: { type: String }, // attachment varchar(255)
  branchstate: { type: String }, // branchstate varchar(50)
  supplierstate: { type: String }, // supplierstate varchar(50)
  auditremarks: { type: String }, // auditremarks varchar(255)
}, { timestamps: false })

export default mongoose.model('Otherpurchaseorder', OtherpurchaseorderSchema, 'otherpurchaseorder')
