import mongoose from 'mongoose'
const { Schema } = mongoose

const PurchasebillSchema = new Schema({
  id: { type: Number }, // id int(11)
  supplier: { type: String }, // supplier varchar(255)
  billno: { type: String }, // billno varchar(20)
  grnno: { type: String }, // grnno varchar(255)
  date: { type: Date }, // date date
  invdate: { type: Date }, // invdate date
  duedays: { type: Number }, // duedays int(11)
  duedate: { type: Date }, // duedate date
  authorizedperson: { type: String }, // authorizedperson varchar(255)
  suppliermobile: { type: String }, // suppliermobile varchar(255)
  area: { type: String }, // area varchar(255)
  supplieremail: { type: String }, // supplieremail varchar(255)
  remarks: { type: String }, // remarks text
  billby: { type: Number }, // billby int(11)
  deleteField: { type: Number }, // delete int(11)
  lock: { type: Number }, // lock int(11)
  enterby: { type: Number }, // enterby int(11)
  enterdatetime: { type: Date }, // enterdatetime datetime
  modifiedby: { type: Number }, // modifiedby int(11)
  modifieddatetime: { type: Date }, // modifieddatetime datetime
  active: { type: Number }, // active int(11)
  branch: { type: Number }, // branch int(11)
  company: { type: Number }, // company int(11)
  action: { type: String }, // action varchar(25)
  subtotal: { type: Number }, // subtotal decimal(15
  totalcgst: { type: Number }, // totalcgst decimal(15
  totalsgst: { type: Number }, // totalsgst decimal(15
  totaligst: { type: Number }, // totaligst decimal(15
  roundoff: { type: Number }, // roundoff float
  total: { type: Number }, // total decimal(15
  approved: { type: String }, // approved varchar(20)
  panfdisc: { type: String }, // panfdisc varchar(255)
  pandfamount: { type: Number }, // pandfamount float
  pandf: { type: Number }, // pandf float
  cgstperpandf: { type: Number }, // cgstperpandf float
  cgstpandf: { type: Number }, // cgstpandf float
  sgstperpandf: { type: Number }, // sgstperpandf float
  sgstpandf: { type: Number }, // sgstpandf float
  igstperpandf: { type: Number }, // igstperpandf float
  igstpandf: { type: Number }, // igstpandf float
  netpandf: { type: Number }, // netpandf float
  cgstperfreight: { type: Number }, // cgstperfreight float
  cgstfreight: { type: Number }, // cgstfreight float
  sgstperfreight: { type: Number }, // sgstperfreight float
  sgstfreight: { type: Number }, // sgstfreight float
  igstperfreight: { type: Number }, // igstperfreight float
  igstfreight: { type: Number }, // igstfreight float
  netfreight: { type: Number }, // netfreight float
  freight: { type: Number }, // freight float
  taxablefreight: { type: Number }, // taxablefreight decimal(10
  gtotal: { type: Number }, // gtotal decimal(15
  costcenter: { type: Number }, // costcenter int(11)
  currency: { type: String }, // currency varchar(255)
  tally: { type: Number }, // tally int(11)
  branchstate: { type: String }, // branchstate varchar(50)
  supplierstate: { type: String }, // supplierstate varchar(50)
  batchno: { type: String }, // batchno varchar(25)
  expirydate: { type: Date }, // expirydate date
  tds: { type: Number }, // tds decimal(10
  tdsdeductedon: { type: Number }, // tdsdeductedon decimal(10
  tdsper: { type: Number }, // tdsper float
  voucherno: { type: Number }, // voucherno int(11)
  purchaseacid: { type: Number }, // purchaseacid int(11)
  customedisc: { type: String }, // customedisc varchar(20)
  customeamount: { type: Number }, // customeamount decimal(10
  custome: { type: Number }, // custome decimal(10
  cgstpercustome: { type: Number }, // cgstpercustome decimal(10
  cgstcustome: { type: Number }, // cgstcustome decimal(10
  sgstpercustome: { type: Number }, // sgstpercustome decimal(10
  sgstcustome: { type: Number }, // sgstcustome decimal(10
  igstpercustome: { type: Number }, // igstpercustome decimal(10
  igstcustome: { type: Number }, // igstcustome decimal(10
  netcustome: { type: Number }, // netcustome decimal(10
  rcm: { type: String }, // rcm varchar(50)
  gstno: { type: String }, // gstno varchar(50)
  invoiceno: { type: String }, // invoiceno varchar(20)
  gstregtype: { type: String }, // gstregtype varchar(25)
  grnnotext: { type: String }, // grnnotext text
  totaltaxamount: { type: Number }, // totaltaxamount decimal(15
  groupId: { type: Number }, // group_id int(11)
  tcsper: { type: Number }, // tcsper decimal(15
  tcsamount: { type: Number }, // tcsamount decimal(15
  aftertcstotal: { type: Number }, // aftertcstotal decimal(15
  rgon: { type: Number }, // rgon int(11)
  subrgon: { type: Number }, // subrgon int(11)
  maincatid: { type: String }, // maincatid varchar(150)
  mainproductid: { type: String }, // mainproductid varchar(150)
  maincategory: { type: String }, // maincategory text
  mainproduct: { type: String }, // mainproduct text
  salesperson: { type: Number }, // salesperson int(11)
  totalqty: { type: Number }, // totalqty decimal(15
  othercharges: { type: Number }, // othercharges decimal(10
  auditremarks: { type: String }, // auditremarks varchar(255)
  headquarter: { type: Number }, // headquarter int(11)
  type2: { type: String }, // type2 varchar(50)
  typeField: { type: String }, // type varchar(50)
  guid: { type: String }, // guid varchar(50)
  gtotal2: { type: Number }, // gtotal2 float
  cgsttotal: { type: Number }, // cgsttotal float
  sgsttotal: { type: Number }, // sgsttotal float
  igsttotal: { type: Number }, // igsttotal float
  kasar: { type: Number }, // kasar decimal(15
}, { timestamps: false })

export default mongoose.model('Purchasebill', PurchasebillSchema, 'purchasebill')
