import mongoose from 'mongoose'
const { Schema } = mongoose

const PurchasereturnSchema = new Schema({
  id: { type: Number }, // id int(11)
  datetime: { type: Date }, // datetime datetime
  reason: { type: String }, // reason text
  company: { type: Number }, // company int(11)
  supplier: { type: Number }, // supplier int(11)
  branch: { type: Number }, // branch int(11)
  deleteField: { type: Number }, // delete int(11)
  lock: { type: Number }, // lock int(11)
  enterby: { type: Number }, // enterby int(11)
  enterdatetime: { type: Date }, // enterdatetime datetime
  modifiedby: { type: Number }, // modifiedby int(11)
  modifieddatetime: { type: Date }, // modifieddatetime datetime
  active: { type: Number }, // active int(11)
  action: { type: String }, // action varchar(25)
  purchaseno: { type: String }, // purchaseno varchar(50)
  approved: { type: String }, // approved varchar(20)
  date: { type: Date }, // date datetime
  area: { type: String }, // area varchar(100)
  suppliermobile: { type: String }, // suppliermobile varchar(20)
  subtotal: { type: Number }, // subtotal decimal(10
  totalcgst: { type: Number }, // totalcgst decimal(10
  totalsgst: { type: Number }, // totalsgst decimal(10
  totaligst: { type: Number }, // totaligst decimal(10
  roundoff: { type: Number }, // roundoff decimal(10
  total: { type: Number }, // total decimal(10
  remarks: { type: String }, // remarks varchar(255)
  billno: { type: String }, // billno varchar(20)
  tally: { type: Number }, // tally int(11)
  voucherno: { type: Number }, // voucherno int(11)
  purchaseacid: { type: Number }, // purchaseacid int(11)
  supplierstate: { type: String }, // supplierstate varchar(25)
  branchstate: { type: String }, // branchstate varchar(25)
  panfdisc: { type: String }, // panfdisc varchar(25)
  pandfamount: { type: Number }, // pandfamount decimal(10
  pandf: { type: Number }, // pandf decimal(10
  cgstperpandf: { type: Number }, // cgstperpandf decimal(10
  cgstpandf: { type: Number }, // cgstpandf decimal(10
  sgstperpandf: { type: Number }, // sgstperpandf decimal(10
  sgstpandf: { type: Number }, // sgstpandf decimal(10
  igstperpandf: { type: Number }, // igstperpandf decimal(10
  igstpandf: { type: Number }, // igstpandf decimal(10
  netpandf: { type: Number }, // netpandf decimal(10
  freight: { type: Number }, // freight decimal(10
  cgstperfreight: { type: Number }, // cgstperfreight decimal(10
  cgstfreight: { type: Number }, // cgstfreight decimal(10
  sgstperfreight: { type: Number }, // sgstperfreight decimal(10
  sgstfreight: { type: Number }, // sgstfreight decimal(10
  igstperfreight: { type: Number }, // igstperfreight decimal(10
  igstfreight: { type: Number }, // igstfreight decimal(10
  netfreight: { type: Number }, // netfreight decimal(10
  approvedby: { type: Number }, // approvedby int(11)
  purchasebillno: { type: Number }, // purchasebillno int(11)
  totaltaxamount: { type: Number }, // totaltaxamount decimal(15
  tds: { type: Number }, // tds decimal(15
  igstcustome: { type: Number }, // igstcustome decimal(15
  cgstcustome: { type: Number }, // cgstcustome decimal(15
  sgstcustome: { type: Number }, // sgstcustome decimal(15
  rcm: { type: Number }, // rcm int(11)
  groupId: { type: Number }, // group_id int(11)
  displayhc: { type: String }, // displayhc varchar(20)
  handlingchargeper: { type: Number }, // handlingchargeper decimal(15
  handlingchargedisc: { type: String }, // handlingchargedisc varchar(20)
  handlingchargeamount: { type: Number }, // handlingchargeamount decimal(15
  handlingcharge: { type: Number }, // handlingcharge decimal(15
  cgstperhandlingcharge: { type: Number }, // cgstperhandlingcharge decimal(15
  cgsthandlingcharge: { type: Number }, // cgsthandlingcharge decimal(15
  sgstperhandlingcharge: { type: Number }, // sgstperhandlingcharge decimal(15
  sgsthandlingcharge: { type: Number }, // sgsthandlingcharge decimal(15
  igstperhandlingcharge: { type: Number }, // igstperhandlingcharge decimal(15
  igsthandlingcharge: { type: Number }, // igsthandlingcharge decimal(15
  nethandlingcharge: { type: Number }, // nethandlingcharge decimal(15
  totalqty: { type: Number }, // totalqty decimal(15
  typeField: { type: String }, // type varchar(20)
  governmentcgstid: { type: Number }, // governmentcgstid int(11)
  governmentsgstid: { type: Number }, // governmentsgstid int(11)
  governmentigstid: { type: Number }, // governmentigstid int(11)
  realbookid: { type: Number }, // realbookid int(11)
  totaladvance: { type: Number }, // totaladvance decimal(15
  advance: { type: Number }, // advance decimal(15
  kasar: { type: Number }, // kasar float
  stockeffect: { type: String }, // stockeffect varchar(50)
  auditremarks: { type: String }, // auditremarks varchar(255)
}, { timestamps: false })

export default mongoose.model('Purchasereturn', PurchasereturnSchema, 'purchasereturn')
