import mongoose from 'mongoose'
const { Schema } = mongoose

const PurchaseitemsSchema = new Schema({
  id: { type: Number }, // id int(11)
  purchaseid: { type: Number }, // purchaseid int(11)
  pid: { type: Number }, // pid int(11)
  quantity: { type: String }, // quantity varchar(255)
  rate: { type: String }, // rate varchar(255)
  taxrate: { type: String }, // taxrate varchar(255)
  discount: { type: String }, // discount varchar(255)
  amount: { type: String }, // amount varchar(255)
  mrp: { type: String }, // mrp varchar(255)
  weight: { type: String }, // weight varchar(255)
  miscdiscount: { type: String }, // miscdiscount varchar(255)
  total: { type: String }, // total varchar(255)
  typeField: { type: String }, // type varchar(11)
  category: { type: String }, // category varchar(50)
  subcategory: { type: String }, // subcategory varchar(25)
  barcode: { type: String }, // barcode varchar(255)
  vat: { type: Number }, // vat float
  addVat: { type: Number }, // add_vat float
  qty: { type: Number }, // qty int(11)
  freeqty: { type: Number }, // freeqty int(11)
  typename: { type: String }, // typename varchar(255)
  gross: { type: Number }, // gross double
  disc: { type: Number }, // disc float
  vatamount: { type: Number }, // vatamount float
  netamount: { type: String }, // netamount varchar(25)
  typedisc: { type: String }, // typedisc varchar(5)
  srno: { type: String }, // srno varchar(25)
  invoiceno: { type: String }, // invoiceno varchar(255)
  amountofducty: { type: String }, // amountofducty varchar(255)
  receiveddirectlyFrom: { type: String }, // receiveddirectly_from varchar(25)
  receivedfrom: { type: String }, // receivedfrom varchar(25)
  qtyperpack: { type: Number }, // qtyperpack float
  packagingsize: { type: String }, // packagingsize varchar(25)
  priceinrs: { type: Number }, // priceinrs float
  exwork: { type: Number }, // exwork float
  total1: { type: Number }, // total1 float
  admexp: { type: Number }, // admexp float
  total2: { type: Number }, // total2 float
  duty: { type: Number }, // duty float
  totalcost: { type: Number }, // totalcost float
  rate2: { type: Number }, // rate2 float
  rate1: { type: Number }, // rate1 float
  deleteField: { type: Number }, // delete int(11)
  lock: { type: Number }, // lock int(11)
  enterby: { type: Number }, // enterby int(11)
  enterdatetime: { type: Date }, // enterdatetime datetime
  modifiedby: { type: Number }, // modifiedby int(11)
  modifieddatetime: { type: Date }, // modifieddatetime datetime
  active: { type: Number }, // active int(11)
  branch: { type: Number }, // branch int(11)
  company: { type: Number }, // company int(11)
  action: { type: String }, // action varchar(25)
  description: { type: String }, // description varchar(255)
  color: { type: String }, // color varchar(255)
  productcode: { type: String }, // productcode varchar(100)
  make: { type: String }, // make varchar(255)
  workproper: { type: String }, // workproper varchar(20)
  binno: { type: String }, // binno varchar(50)
  addtds: { type: Number }, // addtds float
  ledgerid: { type: Number }, // ledgerid int(11)
  partno: { type: String }, // partno varchar(255)
  vatper: { type: Number }, // vatper float
  addvatper: { type: Number }, // addvatper float
  discper: { type: Number }, // discper float
  addvat: { type: Number }, // addvat float
  sgstper: { type: Number }, // sgstper float
  sgst: { type: Number }, // sgst float
  cgstper: { type: Number }, // cgstper float
  cgst: { type: Number }, // cgst float
  igstper: { type: Number }, // igstper float
  igst: { type: Number }, // igst float
  hsncode: { type: String }, // hsncode varchar(30)
  assetid: { type: Number }, // assetid int(11)
  uom: { type: Number }, // uom int(11)
  branchstate: { type: String }, // branchstate varchar(255)
  supplierstate: { type: String }, // supplierstate varchar(255)
  taxamount: { type: Number }, // taxamount decimal(10
  rcmcgstper: { type: Number }, // rcmcgstper decimal(10
  rcmsgstper: { type: Number }, // rcmsgstper decimal(10
  rcmigstper: { type: Number }, // rcmigstper decimal(10
  rcmcgst: { type: Number }, // rcmcgst decimal(10
  rcmsgst: { type: Number }, // rcmsgst decimal(10
  rcmigst: { type: Number }, // rcmigst decimal(10
  cessper: { type: Number }, // cessper float
  cessamount: { type: Number }, // cessamount decimal(15
  costid: { type: Number }, // costid int(11)
}, { timestamps: false })

export default mongoose.model('Purchaseitems', PurchaseitemsSchema, 'purchaseitems')
