import mongoose from 'mongoose'
const { Schema } = mongoose

const SalesorderSchema = new Schema({
  id: { type: Number }, // id int(11)
  salesorderno: { type: String }, // salesorderno varchar(20)
  salesorderdate: { type: Date }, // salesorderdate date
  client: { type: String }, // client varchar(255)
  deliverydate: { type: Date }, // deliverydate date
  salesperson: { type: String }, // salesperson varchar(255)
  gtotal: { type: Number }, // gtotal float
  deleteField: { type: Number }, // delete int(11)
  lock: { type: Number }, // lock int(11)
  enterby: { type: Number }, // enterby int(11)
  enterdatetime: { type: Date }, // enterdatetime datetime
  modifiedby: { type: Number }, // modifiedby int(11)
  modifieddatetime: { type: Date }, // modifieddatetime datetime
  active: { type: Number }, // active int(11)
  branch: { type: Number }, // branch int(11)
  company: { type: Number }, // company int(11)
  action: { type: String }, // action varchar(25)
  entrytype: { type: String }, // entrytype varchar(20)
  attachment: { type: String }, // attachment varchar(255)
  toutstanding: { type: Number }, // toutstanding float
  location: { type: Number }, // location int(11)
  eid: { type: Number }, // eid int(11)
  subtotal: { type: Number }, // subtotal decimal(15
  totalcgst: { type: Number }, // totalcgst float
  totalsgst: { type: Number }, // totalsgst float
  totaligst: { type: Number }, // totaligst float
  roundoff: { type: Number }, // roundoff float
  gstno: { type: String }, // gstno varchar(50)
  panno: { type: String }, // panno varchar(50)
  aadharcardno: { type: String }, // aadharcardno varchar(50)
  pdc: { type: String }, // pdc varchar(50)
  paymenttotal: { type: Number }, // paymenttotal float
  area: { type: String }, // area varchar(255)
  panfdisc: { type: Number }, // panfdisc float
  pandfamount: { type: Number }, // pandfamount float
  pandf: { type: Number }, // pandf float
  cgstperpandf: { type: Number }, // cgstperpandf float
  cgstpandf: { type: Number }, // cgstpandf float
  sgstperpandf: { type: Number }, // sgstperpandf float
  sgstpandf: { type: Number }, // sgstpandf float
  igstperpandf: { type: Number }, // igstperpandf float
  igstpandf: { type: Number }, // igstpandf float
  netpandf: { type: Number }, // netpandf float
  cgstperfreight: { type: Number }, // cgstperfreight float
  cgstfreight: { type: Number }, // cgstfreight float
  sgstperfreight: { type: Number }, // sgstperfreight float
  sgstfreight: { type: Number }, // sgstfreight float
  igstperfreight: { type: Number }, // igstperfreight float
  igstfreight: { type: Number }, // igstfreight float
  netfreight: { type: Number }, // netfreight float
  freight: { type: Number }, // freight float
  coupon: { type: String }, // coupon varchar(20)
  couponno: { type: Number }, // couponno int(11)
  coupontype: { type: String }, // coupontype varchar(20)
  couponamt: { type: Number }, // couponamt float
  amcfreeyear: { type: String }, // amcfreeyear varchar(100)
  commission: { type: String }, // commission varchar(20)
  cledgerid: { type: Number }, // cledgerid int(11)
  commissionamt: { type: Number }, // commissionamt float
  consignee: { type: String }, // consignee varchar(255)
  labname: { type: String }, // labname varchar(100)
  freewarranty: { type: String }, // freewarranty varchar(100)
  otherfreematerial: { type: String }, // otherfreematerial varchar(100)
  pannumber: { type: String }, // pannumber varchar(100)
  thirdpartyname: { type: String }, // thirdpartyname varchar(100)
  couponqty: { type: Number }, // couponqty float
  roff: { type: Number }, // roff float
  leadby: { type: Number }, // leadby int(11)
  invoicingname: { type: Number }, // invoicingname int(11)
  attach: { type: String }, // attach text
  servicetext: { type: String }, // servicetext varchar(100)
  typeofservices: { type: String }, // typeofservices varchar(100)
  otherservices: { type: String }, // otherservices varchar(100)
  otherpayouts: { type: String }, // otherpayouts varchar(100)
  otherpayoutsamt: { type: Number }, // otherpayoutsamt float
  foc: { type: String }, // foc varchar(100)
  amc: { type: String }, // amc varchar(100)
  warranty: { type: String }, // warranty varchar(100)
  attachment1: { type: String }, // attachment1 text
  attachment2: { type: String }, // attachment2 text
  attachment3: { type: String }, // attachment3 text
  attachment4: { type: String }, // attachment4 text
  attachment5: { type: String }, // attachment5 text
  pdcqty: { type: Number }, // pdcqty float
  address: { type: String }, // address text
  consigneeaddress: { type: String }, // consigneeaddress text
  mobile: { type: String }, // mobile varchar(50)
  email: { type: String }, // email varchar(50)
  disc: { type: String }, // disc varchar(255)
  famount: { type: Number }, // famount decimal(15
  typedisc: { type: String }, // typedisc varchar(255)
  branchstate: { type: String }, // branchstate varchar(50)
  customerstate: { type: String }, // customerstate varchar(50)
  buyback: { type: Number }, // buyback float
  serialno: { type: Number }, // serialno float
  tally: { type: Number }, // tally int(11)
  batchnumber: { type: String }, // batchnumber varchar(255)
  buyerstate: { type: String }, // buyerstate varchar(25)
  consigneestate: { type: String }, // consigneestate varchar(25)
  clientpo: { type: String }, // clientpo varchar(50)
  podate: { type: Date }, // podate date
  printtype: { type: String }, // printtype varchar(50)
  voucherno: { type: Number }, // voucherno int(11)
  salesacid: { type: Number }, // salesacid int(11)
  approved: { type: String }, // approved varchar(15)
  ordername: { type: String }, // ordername varchar(25)
  totaltaxamount: { type: Number }, // totaltaxamount decimal(15
  totalqty: { type: Number }, // totalqty decimal(15
  buybackproduct: { type: Number }, // buybackproduct int(11)
  headquarter: { type: Number }, // headquarter int(11)
  buybackproductsrno: { type: String }, // buybackproductsrno text
}, { timestamps: false })

export default mongoose.model('Salesorder', SalesorderSchema, 'salesorder')
