import mongoose from 'mongoose'
const { Schema } = mongoose

const SalesbillSchema = new Schema({
  id: { type: Number }, // id int(11)
  salesbillno: { type: String }, // salesbillno varchar(100)
  client: { type: Number }, // client int(11)
  saleschallanno: { type: Number }, // saleschallanno int(11)
  date: { type: Date }, // date date
  totalcgst: { type: Number }, // totalcgst decimal(10
  totalsgst: { type: Number }, // totalsgst decimal(10
  totaligst: { type: Number }, // totaligst decimal(10
  total: { type: Number }, // total float
  status: { type: String }, // status varchar(255)
  deleteField: { type: Number }, // delete int(11)
  lock: { type: Number }, // lock int(11)
  enterby: { type: Number }, // enterby int(11)
  enterdatetime: { type: Date }, // enterdatetime datetime
  modifiedby: { type: Number }, // modifiedby int(11)
  modifieddatetime: { type: Date }, // modifieddatetime datetime
  active: { type: Number }, // active int(11)
  branch: { type: Number }, // branch int(11)
  company: { type: Number }, // company int(11)
  action: { type: String }, // action varchar(25)
  pdc: { type: String }, // pdc varchar(20)
  typeField: { type: String }, // type varchar(100)
  subtotal: { type: Number }, // subtotal decimal(15
  roundoff: { type: Number }, // roundoff float
  approved: { type: String }, // approved varchar(20)
  godown: { type: Number }, // godown int(11)
  area: { type: String }, // area varchar(255)
  panfdisc: { type: Number }, // panfdisc float
  pandfamount: { type: Number }, // pandfamount float
  pandf: { type: Number }, // pandf float
  cgstperpandf: { type: Number }, // cgstperpandf float
  cgstpandf: { type: Number }, // cgstpandf float
  sgstperpandf: { type: Number }, // sgstperpandf float
  sgstpandf: { type: Number }, // sgstpandf float
  igstperpandf: { type: Number }, // igstperpandf float
  igstpandf: { type: Number }, // igstpandf float
  netpandf: { type: Number }, // netpandf float
  cgstperfreight: { type: Number }, // cgstperfreight float
  cgstfreight: { type: Number }, // cgstfreight float
  sgstperfreight: { type: Number }, // sgstperfreight float
  sgstfreight: { type: Number }, // sgstfreight float
  igstperfreight: { type: Number }, // igstperfreight float
  igstfreight: { type: Number }, // igstfreight float
  netfreight: { type: Number }, // netfreight float
  freight: { type: Number }, // freight float
  location: { type: Number }, // location int(11)
  clientpo: { type: String }, // clientpo varchar(50)
  podate: { type: Date }, // podate date
  couriercompany: { type: String }, // couriercompany varchar(50)
  courierdocket: { type: String }, // courierdocket varchar(50)
  remarks: { type: String }, // remarks varchar(255)
  terms: { type: String }, // terms text
  salesorderno: { type: Number }, // salesorderno int(11)
  materialissueno: { type: String }, // materialissueno varchar(255)
  consignee: { type: String }, // consignee varchar(255)
  duedays: { type: Number }, // duedays int(11)
  duedate: { type: Date }, // duedate date
  ewaybill: { type: String }, // ewaybill varchar(20)
  roff: { type: Number }, // roff float
  billfrom: { type: String }, // billfrom varchar(20)
  address: { type: String }, // address text
  consigneeaddress: { type: String }, // consigneeaddress text
  mobile: { type: String }, // mobile varchar(20)
  email: { type: String }, // email varchar(20)
  gstno: { type: String }, // gstno varchar(20)
  branchstate: { type: String }, // branchstate varchar(50)
  customerstate: { type: String }, // customerstate varchar(50)
  disc: { type: String }, // disc varchar(50)
  famount: { type: String }, // famount varchar(255)
  typedisc: { type: String }, // typedisc varchar(50)
  gtotal: { type: String }, // gtotal varchar(255)
  tally: { type: Number }, // tally int(11)
  buyerstate: { type: String }, // buyerstate varchar(20)
  consigneestate: { type: String }, // consigneestate varchar(20)
  printtype: { type: String }, // printtype varchar(50)
  voucherno: { type: Number }, // voucherno int(11)
  salesacid: { type: Number }, // salesacid int(11)
  consigneename: { type: String }, // consigneename varchar(100)
  consigneepincode: { type: String }, // consigneepincode varchar(50)
  consigneeemail: { type: String }, // consigneeemail varchar(50)
  consigneegstno: { type: String }, // consigneegstno varchar(50)
  consigneemobile: { type: String }, // consigneemobile varchar(25)
  approvedby: { type: Number }, // approvedby int(11)
  ordername: { type: String }, // ordername varchar(25)
  labname: { type: String }, // labname varchar(50)
  receipttotal: { type: Number }, // receipttotal decimal(15
  ewaybillno: { type: String }, // ewaybillno varchar(50)
  printbankdetails: { type: Number }, // printbankdetails int(11)
  totaltaxamount: { type: Number }, // totaltaxamount decimal(15
  advance: { type: Number }, // advance decimal(15
  issuenotext: { type: String }, // issuenotext text
  amcid: { type: Number }, // amcid int(11)
  salesperson: { type: Number }, // salesperson int(11)
  groupId: { type: Number }, // group_id int(11)
  printbankdetails2: { type: Number }, // printbankdetails2 int(11)
  totalqty: { type: Number }, // totalqty decimal(15
  tcsper: { type: Number }, // tcsper decimal(15
  tcsamount: { type: Number }, // tcsamount decimal(15
  aftertcstotal: { type: Number }, // aftertcstotal decimal(15
  maincatid: { type: String }, // maincatid varchar(150)
  mainproductid: { type: String }, // mainproductid varchar(150)
  maincategory: { type: String }, // maincategory text
  mainproduct: { type: String }, // mainproduct text
  rgon: { type: Number }, // rgon int(11)
  subrgon: { type: Number }, // subrgon int(11)
  einvoice: { type: Number }, // einvoice int(11)
  displocation: { type: String }, // displocation varchar(20)
  disppin: { type: String }, // disppin varchar(50)
  dispstcd: { type: String }, // dispstcd varchar(50)
  docperddtlsinvstdate: { type: Date }, // docperddtlsinvstdate date
  docperddtlsinvenddate: { type: Date }, // docperddtlsinvenddate date
  transid: { type: String }, // transid varchar(255)
  transname: { type: String }, // transname varchar(255)
  distance: { type: Number }, // distance float
  transdocno: { type: String }, // transdocno varchar(255)
  transdocdate: { type: Date }, // transdocdate date
  vehno: { type: String }, // vehno varchar(255)
  totalcess: { type: Number }, // totalcess decimal(15
  exportshipbno: { type: String }, // exportshipbno varchar(50)
  exportshipdate: { type: String }, // exportshipdate varchar(50)
  exportsport: { type: String }, // exportsport varchar(50)
  exportsrefclm: { type: String }, // exportsrefclm varchar(50)
  exportsforcur: { type: String }, // exportsforcur varchar(50)
  exportscntcode: { type: String }, // exportscntcode varchar(50)
  exportsexpduty: { type: String }, // exportsexpduty varchar(50)
  couriergstno: { type: String }, // couriergstno varchar(25)
  vehtype: { type: String }, // vehtype varchar(20)
  transmode: { type: String }, // transmode varchar(20)
  ackno: { type: String }, // AckNo varchar(150)
  ackdt: { type: String }, // AckDt varchar(100)
  irn: { type: String }, // Irn varchar(255)
  signedinvoice: { type: String }, // SignedInvoice text
  signedqrcode: { type: String }, // SignedQRCode text
  einvoiceStatus: { type: String }, // einvoice_Status varchar(150)
  ewbno: { type: String }, // EwbNo varchar(150)
  ewbdt: { type: String }, // EwbDt varchar(150)
  ewbvalidtill: { type: String }, // EwbValidTill varchar(150)
  branchpin: { type: String }, // branchpin varchar(20)
  suptyp: { type: String }, // suptyp varchar(10)
  portid: { type: Number }, // portid int(11)
  shippingbillno: { type: String }, // shippingbillno varchar(25)
  shippingbilldate: { type: Date }, // shippingbilldate date
  credittransfer: { type: String }, // credittransfer varchar(20)
  directdebit: { type: String }, // directdebit varchar(20)
  paymentinstruction: { type: String }, // paymentinstruction varchar(100)
  dispatchaddress: { type: String }, // dispatchaddress varchar(100)
  dispatcharea: { type: String }, // dispatcharea varchar(20)
  dispatchcity: { type: String }, // dispatchcity varchar(20)
  dispatchpincode: { type: Number }, // dispatchpincode int(11)
  dispatchstatecode: { type: String }, // dispatchstatecode varchar(20)
  dispatchgstno: { type: String }, // dispatchgstno varchar(20)
  auditremarks: { type: String }, // auditremarks varchar(255)
  billtype: { type: String }, // billtype varchar(20)
  headquarter: { type: Number }, // headquarter int(11)
}, { timestamps: false })

export default mongoose.model('Salesbill', SalesbillSchema, 'salesbill')
