import mongoose from 'mongoose'
const { Schema } = mongoose

const SalesreturnSchema = new Schema({
  id: { type: Number }, // id int(11)
  branchstate: { type: String }, // branchstate varchar(25)
  date: { type: Date }, // date date
  salesbillno: { type: String }, // salesbillno varchar(50)
  reason: { type: String }, // reason text
  company: { type: String }, // company varchar(255)
  client: { type: Number }, // client int(11)
  totalcgst: { type: Number }, // totalcgst decimal(10
  totalsgst: { type: Number }, // totalsgst decimal(10
  totaligst: { type: Number }, // totaligst decimal(10
  total: { type: Number }, // total decimal(10
  branch: { type: Number }, // branch int(11)
  status: { type: String }, // status varchar(10)
  deleteField: { type: Number }, // delete int(11)
  lock: { type: Number }, // lock int(11)
  enterby: { type: Number }, // enterby int(11)
  enterdatetime: { type: Date }, // enterdatetime datetime
  modifiedby: { type: Number }, // modifiedby int(11)
  modifieddatetime: { type: Date }, // modifieddatetime datetime
  active: { type: Number }, // active int(11)
  action: { type: String }, // action varchar(25)
  approved: { type: String }, // approved varchar(20)
  subtotal: { type: Number }, // subtotal decimal(10
  roundoff: { type: Number }, // roundoff decimal(10
  tally: { type: Number }, // tally int(11)
  voucherno: { type: Number }, // voucherno int(11)
  salesacid: { type: Number }, // salesacid int(11)
  remarks: { type: String }, // remarks text
  pandfamount: { type: Number }, // pandfamount decimal(10
  pandf: { type: Number }, // pandf decimal(10
  cgstperpandf: { type: Number }, // cgstperpandf decimal(10
  cgstpandf: { type: Number }, // cgstpandf decimal(10
  sgstperpandf: { type: Number }, // sgstperpandf decimal(10
  sgstpandf: { type: Number }, // sgstpandf decimal(10
  igstperpandf: { type: Number }, // igstperpandf decimal(10
  igstpandf: { type: Number }, // igstpandf decimal(10
  netpandf: { type: Number }, // netpandf decimal(10
  freight: { type: Number }, // freight decimal(10
  cgstperfreight: { type: Number }, // cgstperfreight decimal(10
  cgstfreight: { type: Number }, // cgstfreight decimal(10
  sgstperfreight: { type: Number }, // sgstperfreight decimal(10
  sgstfreight: { type: Number }, // sgstfreight decimal(10
  igstperfreight: { type: Number }, // igstperfreight decimal(10
  igstfreight: { type: Number }, // igstfreight decimal(10
  netfreight: { type: Number }, // netfreight decimal(10
  roff: { type: Number }, // roff decimal(10
  gtotal: { type: Number }, // gtotal decimal(10
  customerstate: { type: String }, // customerstate varchar(20)
  panfdisc: { type: String }, // panfdisc varchar(20)
  salesbillid: { type: Number }, // salesbillid int(11)
  salesreturnno: { type: String }, // salesreturnno varchar(25)
  approvedby: { type: Number }, // approvedby int(11)
  gstno: { type: String }, // gstno varchar(25)
  totaltaxamount: { type: Number }, // totaltaxamount decimal(15
  disc: { type: Number }, // disc decimal(15
  typedisc: { type: String }, // typedisc varchar(20)
  famount: { type: Number }, // famount decimal(15
  salereturnperson: { type: Number }, // salereturnperson int(11)
  rgon: { type: Number }, // rgon int(11)
  subrgon: { type: Number }, // subrgon int(11)
  maincatid: { type: String }, // maincatid varchar(150)
  mainproductid: { type: String }, // mainproductid varchar(150)
  maincategory: { type: String }, // maincategory text
  mainproduct: { type: String }, // mainproduct text
  salesperson: { type: Number }, // salesperson int(11)
  groupId: { type: Number }, // group_id int(11)
  tcsamount: { type: Number }, // tcsamount decimal(15
  einvoice: { type: Number }, // einvoice int(11)
  ackno: { type: String }, // AckNo varchar(150)
  ackdt: { type: String }, // AckDt varchar(150)
  irn: { type: String }, // Irn varchar(150)
  signedinvoice: { type: String }, // SignedInvoice text
  signedqrcode: { type: String }, // SignedQRCode text
  einvoiceStatus: { type: String }, // einvoice_Status varchar(150)
  ewbno: { type: String }, // EwbNo varchar(150)
  ewbdt: { type: String }, // EwbDt varchar(150)
  ewbvalidtill: { type: String }, // EwbValidTill varchar(150)
  suptyp: { type: String }, // suptyp varchar(20)
  portid: { type: Number }, // portid int(11)
  shippingbillno: { type: String }, // shippingbillno varchar(100)
  shippingbilldate: { type: Date }, // shippingbilldate date
  exportsexpduty: { type: String }, // exportsexpduty varchar(50)
  credittransfer: { type: String }, // credittransfer varchar(50)
  directdebit: { type: String }, // directdebit varchar(50)
  paymentinstruction: { type: String }, // paymentinstruction varchar(100)
  couriercompany: { type: String }, // couriercompany varchar(50)
  couriergstno: { type: String }, // couriergstno varchar(50)
  distance: { type: Number }, // distance int(11)
  vehno: { type: String }, // vehno varchar(50)
  vehtype: { type: String }, // vehtype varchar(50)
  courierdocket: { type: String }, // courierdocket varchar(50)
  transdocdate: { type: Date }, // transdocdate date
  transmode: { type: String }, // transmode varchar(50)
  branchpin: { type: String }, // branchpin varchar(20)
  clientpincode: { type: String }, // clientpincode varchar(20)
  clientemail: { type: String }, // clientemail varchar(20)
  clientmobile: { type: String }, // clientmobile varchar(20)
  clientaddress: { type: String }, // clientaddress varchar(120)
  ewaybill: { type: String }, // ewaybill varchar(10)
  auditremarks: { type: String }, // auditremarks varchar(255)
  stockeffect: { type: String }, // stockeffect varchar(50)
  headquarter: { type: Number }, // headquarter int(11)
  typeField: { type: String }, // type varchar(10)
}, { timestamps: false })

export default mongoose.model('Salesreturn', SalesreturnSchema, 'salesreturn')
