import mongoose from 'mongoose'
const { Schema } = mongoose

const SalesSchema = new Schema({
  id: { type: Number }, // id int(11)
  salesorderdate: { type: Date }, // salesorderdate date
  invoicenumber: { type: String }, // invoicenumber varchar(255)
  client: { type: String }, // client varchar(255)
  remark: { type: String }, // remark varchar(255)
  account: { type: String }, // account varchar(12)
  typeField: { type: String }, // type varchar(25)
  status: { type: String }, // status varchar(25)
  notes: { type: String }, // notes text
  vouchertype: { type: String }, // vouchertype varchar(25)
  voucherno: { type: String }, // voucherno varchar(25)
  gross: { type: Number }, // gross float
  discount: { type: Number }, // discount float
  servicetax: { type: Number }, // servicetax float
  educess: { type: Number }, // educess float
  hscs: { type: Number }, // hscs float
  roundoff: { type: Number }, // roundoff float
  total: { type: Number }, // total float
  deliverydatetime: { type: Date }, // deliverydatetime datetime
  startdate: { type: Date }, // startdate date
  enddate: { type: Date }, // enddate date
  discountper: { type: Number }, // discountper float
  sbctax: { type: Number }, // sbctax float
  kkctax: { type: Number }, // kkctax float
  freight: { type: Number }, // freight float
  pono: { type: String }, // pono varchar(50)
  podate: { type: Date }, // podate date
  sampledate: { type: Date }, // sampledate datetime
  isduplicate: { type: String }, // isduplicate varchar(10)
  cess1per: { type: Number }, // cess1per float
  cess2per: { type: Number }, // cess2per float
  stper: { type: Number }, // stper float
  cgstper: { type: Number }, // cgstper float
  cgst: { type: Number }, // cgst float
  sgstper: { type: Number }, // sgstper float
  sgst: { type: Number }, // sgst float
  igstper: { type: Number }, // igstper float
  igst: { type: Number }, // igst float
  gst: { type: Number }, // gst int(11)
  printtype: { type: String }, // printtype varchar(25)
  paymentterms: { type: String }, // paymentterms varchar(50)
  cessper: { type: Number }, // cessper float
  cess: { type: Number }, // cess float
  placeofsupply: { type: String }, // placeofsupply varchar(150)
  statecode: { type: String }, // statecode varchar(100)
  billingaddress: { type: String }, // billingaddress text
  customerstate: { type: String }, // customerstate varchar(255)
  companystate: { type: String }, // companystate varchar(255)
  company: { type: Number }, // company int(11)
  tcsper: { type: Number }, // tcsper float
  tcsamount: { type: Number }, // tcsamount decimal(15
  aftertcstotal: { type: Number }, // aftertcstotal decimal(15
  ackno: { type: String }, // AckNo varchar(255)
  ackdt: { type: String }, // AckDt varchar(255)
  irn: { type: String }, // Irn varchar(255)
  signedinvoice: { type: String }, // SignedInvoice text
  signedqrcode: { type: String }, // SignedQRCode text
  einvoiceStatus: { type: String }, // einvoice_Status varchar(255)
  ewbno: { type: String }, // EwbNo varchar(255)
  ewbdt: { type: String }, // EwbDt varchar(255)
  ewbvalidtill: { type: String }, // EwbValidTill varchar(255)
  couriercompany: { type: String }, // couriercompany varchar(50)
  couriergstno: { type: String }, // couriergstno varchar(50)
  distance: { type: String }, // distance varchar(50)
  vehno: { type: String }, // vehno varchar(50)
  vehtype: { type: String }, // vehtype varchar(50)
  courierdocket: { type: String }, // courierdocket varchar(50)
  transdocdate: { type: Date }, // transdocdate date
  transmode: { type: String }, // transmode varchar(50)
  clientpin: { type: Number }, // clientpin int(11)
  branchpin: { type: Number }, // branchpin int(11)
  ewaybill: { type: String }, // ewaybill varchar(20)
  deleteField: { type: Number }, // delete int(11)
  active: { type: Number }, // active int(11)
  approved: { type: String }, // approved varchar(50)
}, { timestamps: false })

export default mongoose.model('Sales', SalesSchema, 'sales')
