import mongoose from 'mongoose'
const { Schema } = mongoose

const ShiftmasterSchema = new Schema({
  id: { type: Number }, // id int(11)
  deleteField: { type: Number }, // delete int(11)
  lock: { type: Number }, // lock int(11)
  active: { type: Number }, // active int(11)
  enterby: { type: Number }, // enterby int(11)
  enterdatetime: { type: Date }, // enterdatetime datetime
  modifiedby: { type: Number }, // modifiedby int(11)
  modifieddatetime: { type: Date }, // modifieddatetime datetime
  shiftname: { type: String }, // shiftname varchar(50)
  branch: { type: Number }, // branch int(11)
  company: { type: Number }, // company int(11)
  action: { type: String }, // action varchar(25)
  intme: { type: String }, // intme varchar(15)
  outtme: { type: String }, // outtme varchar(15)
  latetme: { type: String }, // latetme varchar(30)
  earliertme: { type: String }, // earliertme varchar(30)
  lunchtmestart: { type: String }, // lunchtmestart varchar(30)
  lunchtmeendt: { type: String }, // lunchtmeendt varchar(30)
  minhours: { type: String }, // minhours varchar(50)
  latemark2: { type: String }, // latemark2 varchar(50)
  early2: { type: String }, // early2 varchar(50)
  halfdayaftertme: { type: String }, // halfdayaftertme varchar(50)
  halfdaybeforetme: { type: String }, // halfdaybeforetme varchar(50)
  f2halfdaylate: { type: String }, // 2halfdaylate varchar(50)
  f2halfdaylate2: { type: String }, // 2halfdaylate2 varchar(50)
  absentaftertme: { type: String }, // absentaftertme varchar(50)
  minminutes: { type: String }, // minminutes varchar(50)
  latemark1ignore: { type: String }, // latemark1ignore varchar(50)
  latemark2ignore: { type: String }, // latemark2ignore varchar(50)
  earlier1ignore: { type: String }, // earlier1ignore varchar(50)
  earlier2ignore: { type: String }, // earlier2ignore varchar(50)
  othours: { type: String }, // othours varchar(50)
  nightshift: { type: String }, // nightshift varchar(50)
  daynightshift: { type: String }, // daynightshift varchar(50)
  teaintme1: { type: String }, // teaintme1 varchar(10)
  teaouttme1: { type: String }, // teaouttme1 varchar(10)
  teaintme2: { type: String }, // teaintme2 varchar(10)
  teaouttme2: { type: String }, // teaouttme2 varchar(10)
  otdeductionmins: { type: String }, // otdeductionmins varchar(50)
  halfminhours: { type: String }, // halfminhours varchar(50)
  halfminminutes: { type: String }, // halfminminutes varchar(50)
}, { timestamps: false })

export default mongoose.model('Shiftmaster', ShiftmasterSchema, 'shiftmaster')
