import mongoose from 'mongoose'
const { Schema } = mongoose

const SupplierproductSchema = new Schema({
  id: { type: Number }, // id int(11)
  shape: { type: String }, // shape varchar(255)
  packetno: { type: String }, // packetno varchar(255)
  diamonddna: { type: String }, // diamonddna varchar(255)
  carats: { type: String }, // carats varchar(255)
  rate: { type: String }, // rate varchar(255)
  rap: { type: String }, // rap varchar(255)
  lab: { type: String }, // lab varchar(255)
  reportno: { type: String }, // reportno varchar(255)
  size: { type: String }, // size varchar(255)
  clarity: { type: Number }, // clarity int(11)
  color: { type: String }, // color varchar(255)
  colorshade: { type: Number }, // colorshade int(11)
  cut: { type: String }, // cut varchar(255)
  flour: { type: String }, // flour varchar(50)
  fluorcolor: { type: String }, // fluorcolor varchar(255)
  luster: { type: String }, // luster varchar(255)
  blackinclusion: { type: String }, // blackinclusion varchar(255)
  tableinclusion: { type: String }, // tableinclusion varchar(255)
  round: { type: String }, // round varchar(255)
  polish: { type: String }, // polish varchar(255)
  sym: { type: String }, // sym varchar(255)
  tblopn: { type: String }, // tblopn varchar(255)
  crnopn: { type: String }, // crnopn varchar(255)
  pavopn: { type: String }, // pavopn varchar(255)
  grdlcrdnopn: { type: String }, // grdlcrdnopn varchar(255)
  inclusionpattern: { type: String }, // inclusionpattern varchar(255)
  diameteravg: { type: String }, // diameteravg varchar(255)
  lwratio: { type: String }, // lwratio varchar(255)
  tabl: { type: String }, // tabl varchar(255)
  crownangle: { type: String }, // crownangle varchar(255)
  crownheight: { type: String }, // crownheight varchar(255)
  countryofrough: { type: String }, // countryofrough varchar(255)
  mineoforigin: { type: String }, // mineoforigin varchar(255)
  roughmine: { type: String }, // roughmine varchar(255)
  keytosymbol: { type: String }, // keytosymbol varchar(255)
  comments: { type: String }, // comments varchar(255)
}, { timestamps: false })

export default mongoose.model('Supplierproduct', SupplierproductSchema, 'supplierproduct')
