import mongoose from 'mongoose'
const { Schema } = mongoose

const Temp202526VoucherSchema = new Schema({
  action: { type: String }, // _action text
  objview: { type: String }, // _objview text
  remoteid: { type: String }, // _remoteid text
  vchkey: { type: String }, // _vchkey text
  vchtype: { type: String }, // _vchtype text
  accountauditentriesList: { type: String }, // accountauditentries_list text
  allledgerentriesList: { type: String }, // allledgerentries_list text
  allowconsumption: { type: String }, // allowconsumption text
  alterid: { type: String }, // alterid text
  asoriginal: { type: String }, // asoriginal text
  aspayslip: { type: String }, // aspayslip text
  attdrecordsList: { type: String }, // attdrecords_list text
  attendanceentriesList: { type: String }, // attendanceentries_list text
  audited: { type: String }, // audited text
  auditentriesList: { type: String }, // auditentries_list text
  basicbasepartyname: { type: String }, // basicbasepartyname text
  basicbuyername: { type: String }, // basicbuyername text
  buyerpinnumber: { type: String }, // buyerpinnumber text
  changevchmode: { type: String }, // changevchmode text
  classname: { type: String }, // classname text
  cmpgstin: { type: String }, // cmpgstin text
  cmpgstisothterritoryassessee: { type: String }, // cmpgstisothterritoryassessee text
  cmpgstregistrationtype: { type: String }, // cmpgstregistrationtype text
  cmpgststate: { type: String }, // cmpgststate text
  consigneecountryname: { type: String }, // consigneecountryname text
  consigneegstin: { type: String }, // consigneegstin text
  consigneemailingname: { type: String }, // consigneemailingname text
  consigneepincode: { type: String }, // consigneepincode text
  consigneepinnumber: { type: String }, // consigneepinnumber text
  consigneestatename: { type: String }, // consigneestatename text
  contritransList: { type: String }, // contritrans_list text
  countryofresidence: { type: String }, // countryofresidence text
  cstformissuetype: { type: String }, // cstformissuetype text
  cstformrecvtype: { type: String }, // cstformrecvtype text
  date: { type: String }, // date text
  diffactualqty: { type: String }, // diffactualqty text
  dutyheaddetailsList: { type: String }, // dutyheaddetails_list text
  effectivedate: { type: String }, // effectivedate text
  enteredby: { type: String }, // enteredby text
  ewaybilldetailsList: { type: String }, // ewaybilldetails_list text
  ewaybillerrorlistList: { type: String }, // ewaybillerrorlist_list text
  exciseopening: { type: String }, // exciseopening text
  excisetaxoverride: { type: String }, // excisetaxoverride text
  excludedtaxationsList: { type: String }, // excludedtaxations_list text
  fbtpaymenttype: { type: String }, // fbtpaymenttype text
  forjobcosting: { type: String }, // forjobcosting text
  gstList: { type: String }, // gst_list text
  gstadvadjdetailsList: { type: String }, // gstadvadjdetails_list text
  gstbuyeraddressList: { type: String }, // gstbuyeraddress_list text
  gstconsigneeaddressList: { type: String }, // gstconsigneeaddress_list text
  gstewayconsigneeaddressList: { type: String }, // gstewayconsigneeaddress_list text
  gstewayconsignoraddressList: { type: String }, // gstewayconsignoraddress_list text
  gstnatureofreturn: { type: String }, // gstnatureofreturn text
  gstnotexported: { type: String }, // gstnotexported text
  gstregistration: { type: String }, // gstregistration text
  gstregistrationtype: { type: String }, // gstregistrationtype text
  guid: { type: String }, // guid text
  haryanavatList: { type: String }, // haryanavat_list text
  hascashflow: { type: String }, // hascashflow text
  hasdiscounts: { type: String }, // hasdiscounts text
  id: { type: String }, // id text
  ignoreeinvvalidation: { type: String }, // ignoreeinvvalidation text
  ignoregstconflictinmig: { type: String }, // ignoregstconflictinmig text
  ignoregstformatvalidation: { type: String }, // ignoregstformatvalidation text
  ignoregstinvalidation: { type: String }, // ignoregstinvalidation text
  ignoregstoptionaluncertain: { type: String }, // ignoregstoptionaluncertain text
  ignoreorigvchdate: { type: String }, // ignoreorigvchdate text
  ignoreposvalidation: { type: String }, // ignoreposvalidation text
  includeadvpymtvch: { type: String }, // includeadvpymtvch text
  invoicedelnotesList: { type: String }, // invoicedelnotes_list text
  invoiceexportlistList: { type: String }, // invoiceexportlist_list text
  invoiceindentlistList: { type: String }, // invoiceindentlist_list text
  invoiceorderlistList: { type: String }, // invoiceorderlist_list text
  irncancelled: { type: String }, // irncancelled text
  irnerrorlistList: { type: String }, // irnerrorlist_list text
  irnjsonexported: { type: String }, // irnjsonexported text
  isblankcheque: { type: String }, // isblankcheque text
  isboenotapplicable: { type: String }, // isboenotapplicable text
  iscancelled: { type: String }, // iscancelled text
  iscommonparty: { type: String }, // iscommonparty text
  iscostcentre: { type: String }, // iscostcentre text
  iscstdelcaredgoodssales: { type: String }, // iscstdelcaredgoodssales text
  isdeclaredtocustoms: { type: String }, // isdeclaredtocustoms text
  isdeleted: { type: String }, // isdeleted text
  isdeletedretained: { type: String }, // isdeletedretained text
  isdeletedvchretained: { type: String }, // isdeletedvchretained text
  isdeliverysameasconsignee: { type: String }, // isdeliverysameasconsignee text
  isdesignatedzoneparty: { type: String }, // isdesignatedzoneparty text
  isdispatchsameasconsignor: { type: String }, // isdispatchsameasconsignor text
  isecommercesupply: { type: String }, // isecommercesupply text
  iseligibleforitc: { type: String }, // iseligibleforitc text
  isewaybillapplicable: { type: String }, // isewaybillapplicable text
  isexcisemanufactureron: { type: String }, // isexcisemanufactureron text
  isexciseoverridden: { type: String }, // isexciseoverridden text
  isexcisesupplyvch: { type: String }, // isexcisesupplyvch text
  isexcisevoucher: { type: String }, // isexcisevoucher text
  isexer1nopoverwrite: { type: String }, // isexer1nopoverwrite text
  isexer3nopoverwrite: { type: String }, // isexer3nopoverwrite text
  isexf2nopoverwrite: { type: String }, // isexf2nopoverwrite text
  isfetchedonly: { type: String }, // isfetchedonly text
  isforjobworkin: { type: String }, // isforjobworkin text
  isgstoverridden: { type: String }, // isgstoverridden text
  isgstovrdncrc: { type: String }, // isgstovrdncrc text
  isgstrefund: { type: String }, // isgstrefund text
  isgstsecsevenapplicable: { type: String }, // isgstsecsevenapplicable text
  isinvoice: { type: String }, // isinvoice text
  isisdvoucher: { type: String }, // isisdvoucher text
  ismstfromsync: { type: String }, // ismstfromsync text
  isnull: { type: String }, // isnull text
  isonhold: { type: String }, // isonhold text
  isopbaltransaction: { type: String }, // isopbaltransaction text
  isoptional: { type: String }, // isoptional text
  isoverseastouristtrans: { type: String }, // isoverseastouristtrans text
  ispostdated: { type: String }, // ispostdated text
  isreversechargeapplicable: { type: String }, // isreversechargeapplicable text
  issecurityonwhenentered: { type: String }, // issecurityonwhenentered text
  isservicetaxoverridden: { type: String }, // isservicetaxoverridden text
  isshippingwithinstate: { type: String }, // isshippingwithinstate text
  isstxnonrealizedvch: { type: String }, // isstxnonrealizedvch text
  issubworkscontract: { type: String }, // issubworkscontract text
  issummary: { type: String }, // issummary text
  issystem: { type: String }, // issystem text
  istcsoverridden: { type: String }, // istcsoverridden text
  istdsoverridden: { type: String }, // istdsoverridden text
  istdstcscashvch: { type: String }, // istdstcscashvch text
  isvatdutypaid: { type: String }, // isvatdutypaid text
  isvatoverridden: { type: String }, // isvatoverridden text
  isvatpaidatcustoms: { type: String }, // isvatpaidatcustoms text
  isvatprincipalaccount: { type: String }, // isvatprincipalaccount text
  isvatrestaxinv: { type: String }, // isvatrestaxinv text
  isvatrestaxinvoice: { type: String }, // isvatrestaxinvoice text
  isvoid: { type: String }, // isvoid text
  masterid: { type: String }, // masterid text
  mfgjournal: { type: String }, // mfgjournal text
  narration: { type: String }, // narration text
  numberingstyle: { type: String }, // numberingstyle text
  oldauditentriesList: { type: String }, // oldauditentries_list text
  orderlinestatus: { type: String }, // orderlinestatus text
  originvoicedetailsList: { type: String }, // originvoicedetails_list text
  ovrdnewaybillapplicability: { type: String }, // ovrdnewaybillapplicability text
  parentId: { type: String }, // parent_id text
  partygstin: { type: String }, // partygstin text
  partygstisothterritoryassessee: { type: String }, // partygstisothterritoryassessee text
  partyledgername: { type: String }, // partyledgername text
  partymailingname: { type: String }, // partymailingname text
  partyname: { type: String }, // partyname text
  partypincode: { type: String }, // partypincode text
  paymentlinkhasmultiref: { type: String }, // paymentlinkhasmultiref text
  payrollmodeofpaymentList: { type: String }, // payrollmodeofpayment_list text
  persistedview: { type: String }, // persistedview text
  placeofsupply: { type: String }, // placeofsupply text
  reference: { type: String }, // reference text
  referencedate: { type: String }, // referencedate text
  resetirnqrcode: { type: String }, // resetirnqrcode text
  statename: { type: String }, // statename text
  stkjrnladdlcostdetailsList: { type: String }, // stkjrnladdlcostdetails_list text
  supplementarydutyheaddetailsList: { type: String }, // supplementarydutyheaddetails_list text
  tempgstadvadjustedList: { type: String }, // tempgstadvadjusted_list text
  tempgstratedetailsList: { type: String }, // tempgstratedetails_list text
  updatesummaryvalues: { type: String }, // updatesummaryvalues text
  useforcompound: { type: String }, // useforcompound text
  useforexcise: { type: String }, // useforexcise text
  useforfinalproduction: { type: String }, // useforfinalproduction text
  useforgainloss: { type: String }, // useforgainloss text
  useforgodowntransfer: { type: String }, // useforgodowntransfer text
  useforinterest: { type: String }, // useforinterest text
  useforservicetax: { type: String }, // useforservicetax text
  usefortaxunittransfer: { type: String }, // usefortaxunittransfer text
  usetrackingnumber: { type: String }, // usetrackingnumber text
  vatadvancepayment: { type: String }, // vatadvancepayment text
  vatadvpay: { type: String }, // vatadvpay text
  vatdealertype: { type: String }, // vatdealertype text
  vatisagnstcancsales: { type: String }, // vatisagnstcancsales text
  vatisassesablecalcvch: { type: String }, // vatisassesablecalcvch text
  vatispurcexempted: { type: String }, // vatispurcexempted text
  vatpartytransreturndate: { type: String }, // vatpartytransreturndate text
  vatpartytransreturnnumber: { type: String }, // vatpartytransreturnnumber text
  vchentrymode: { type: String }, // vchentrymode text
  vchgstclass: { type: String }, // vchgstclass text
  vchgststatusisapplicable: { type: String }, // vchgststatusisapplicable text
  vchgststatusisbranchtransferout: { type: String }, // vchgststatusisbranchtransferout text
  vchgststatusisexcluded: { type: String }, // vchgststatusisexcluded text
  vchgststatusisgstr2bindiffperiod: { type: String }, // vchgststatusisgstr2bindiffperiod text
  vchgststatusisgstr2bmismatch: { type: String }, // vchgststatusisgstr2bmismatch text
  vchgststatusisgstr2bonlyinbooks: { type: String }, // vchgststatusisgstr2bonlyinbooks text
  vchgststatusisgstr2bonlyinportal: { type: String }, // vchgststatusisgstr2bonlyinportal text
  vchgststatusisgstr2breconciled: { type: String }, // vchgststatusisgstr2breconciled text
  vchgststatusisincluded: { type: String }, // vchgststatusisincluded text
  vchgststatusisoptionaluncertain: { type: String }, // vchgststatusisoptionaluncertain text
  vchgststatusisoverrdn: { type: String }, // vchgststatusisoverrdn text
  vchgststatusisreteffdateoverrdn: { type: String }, // vchgststatusisreteffdateoverrdn text
  vchgststatusisretindiffdate: { type: String }, // vchgststatusisretindiffdate text
  vchgststatusisstatindiffdate: { type: String }, // vchgststatusisstatindiffdate text
  vchgststatusissystemsummary: { type: String }, // vchgststatusissystemsummary text
  vchgststatusisuncertain: { type: String }, // vchgststatusisuncertain text
  vchgststatusmainsectionexcluded: { type: String }, // vchgststatusmainsectionexcluded text
  vchstatusdate: { type: String }, // vchstatusdate text
  vchstatusiscancelled: { type: String }, // vchstatusiscancelled text
  vchstatusisdeleted: { type: String }, // vchstatusisdeleted text
  vchstatusisfetchedonly: { type: String }, // vchstatusisfetchedonly text
  vchstatusisopeningbalance: { type: String }, // vchstatusisopeningbalance text
  vchstatusisoptional: { type: String }, // vchstatusisoptional text
  vchstatusisunregisteredrcm: { type: String }, // vchstatusisunregisteredrcm text
  vchstatusisvchnumused: { type: String }, // vchstatusisvchnumused text
  vchstatustaxadjustment: { type: String }, // vchstatustaxadjustment text
  vchstatustaxunit: { type: String }, // vchstatustaxunit text
  vchstatusvouchertype: { type: String }, // vchstatusvouchertype text
  voucherkey: { type: String }, // voucherkey text
  vouchernumber: { type: String }, // vouchernumber text
  vouchernumberseries: { type: String }, // vouchernumberseries text
  voucherretainkey: { type: String }, // voucherretainkey text
  vouchertypename: { type: String }, // vouchertypename text
}, { timestamps: false })

export default mongoose.model('Temp202526Voucher', Temp202526VoucherSchema, 'temp_2025_26_voucher')
